//! CartLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CartLine;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CartLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCartLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cart_id")]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    pub quantity: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CartLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCartLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cart_id")]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    pub quantity: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CartLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCartLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cart_id")]
    pub cart_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
}

impl PatchCartLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.cart_id.is_some() || self.item_id.is_some() || self.quantity.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CartLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CartLineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CartLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CartLineListResponseDto {
    /// List of items
    pub items: Vec<CartLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CartLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CartLineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CartLineSummaryDto {
    pub id: Uuid,
    pub cart_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CartLine> for CartLineResponseDto {
    fn from(entity: CartLine) -> Self {
        Self {
            id: entity.id,
            cart_id: entity.cart_id,
            item_id: entity.item_id,
            quantity: entity.quantity,
            metadata: entity.metadata,
        }
    }
}

impl From<CartLine> for CartLineSummaryDto {
    fn from(entity: CartLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            cart_id: entity.cart_id,
            item_id: entity.item_id,
            quantity: entity.quantity,
            created_at,
        }
    }
}

impl From<CreateCartLineDto> for CartLine {
    fn from(dto: CreateCartLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            cart_id: dto.cart_id,
            item_id: dto.item_id,
            quantity: dto.quantity,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CartLine> for CartLineResponseDto {
    fn from(entity: &CartLine) -> Self {
        Self {
            id: entity.id.clone(),
            cart_id: entity.cart_id.clone(),
            item_id: entity.item_id.clone(),
            quantity: entity.quantity.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCartLineDto> for CartLine {
    fn from_create_dto(dto: CreateCartLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(CartLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCartLineDto> for CartLine {
    fn apply_update(mut self, dto: UpdateCartLineDto) -> backbone_core::ServiceResult<Self> {
        self.cart_id = dto.cart_id;
        self.item_id = dto.item_id;
        self.quantity = dto.quantity;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CartLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
