//! Cart DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Cart;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::StorefrontCartState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Cart
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCartDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "visitor_id")]
    pub visitor_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    pub state: StorefrontCartState,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "coupon_code")]
    pub coupon_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "delivery_carrier_id")]
    pub delivery_carrier_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "placed_at")]
    pub placed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Cart
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCartDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "visitor_id")]
    pub visitor_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    pub state: StorefrontCartState,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "coupon_code")]
    pub coupon_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "delivery_carrier_id")]
    pub delivery_carrier_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "placed_at")]
    pub placed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Cart
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCartDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_id")]
    pub visitor_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<StorefrontCartState>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "coupon_code")]
    pub coupon_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "delivery_carrier_id")]
    pub delivery_carrier_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "placed_at")]
    pub placed_at: Option<DateTime<Utc>>,
}

impl PatchCartDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.visitor_id.is_some() || self.portal_user_id.is_some() || self.party_id.is_some() || self.state.is_some() || self.coupon_code.is_some() || self.delivery_carrier_id.is_some() || self.placed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Cart entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CartResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub visitor_id: Uuid,
    pub portal_user_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub state: StorefrontCartState,
    pub coupon_code: Option<String>,
    pub delivery_carrier_id: Option<Uuid>,
    pub placed_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Cart entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CartListResponseDto {
    /// List of items
    pub items: Vec<CartResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CartListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CartResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CartSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub visitor_id: Uuid,
    pub portal_user_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Cart> for CartResponseDto {
    fn from(entity: Cart) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            visitor_id: entity.visitor_id,
            portal_user_id: entity.portal_user_id,
            party_id: entity.party_id,
            state: entity.state,
            coupon_code: entity.coupon_code,
            delivery_carrier_id: entity.delivery_carrier_id,
            placed_at: entity.placed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Cart> for CartSummaryDto {
    fn from(entity: Cart) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            visitor_id: entity.visitor_id,
            portal_user_id: entity.portal_user_id,
            created_at,
        }
    }
}

impl From<CreateCartDto> for Cart {
    fn from(dto: CreateCartDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            visitor_id: dto.visitor_id,
            portal_user_id: dto.portal_user_id,
            party_id: dto.party_id,
            state: dto.state,
            coupon_code: dto.coupon_code,
            delivery_carrier_id: dto.delivery_carrier_id,
            placed_at: dto.placed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Cart> for CartResponseDto {
    fn from(entity: &Cart) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            visitor_id: entity.visitor_id.clone(),
            portal_user_id: entity.portal_user_id.clone(),
            party_id: entity.party_id.clone(),
            state: entity.state.clone(),
            coupon_code: entity.coupon_code.clone(),
            delivery_carrier_id: entity.delivery_carrier_id.clone(),
            placed_at: entity.placed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCartDto> for Cart {
    fn from_create_dto(dto: CreateCartDto) -> backbone_core::ServiceResult<Self> {
        Ok(Cart::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCartDto> for Cart {
    fn apply_update(mut self, dto: UpdateCartDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.visitor_id = dto.visitor_id;
        self.portal_user_id = dto.portal_user_id;
        self.party_id = dto.party_id;
        self.state = dto.state;
        self.coupon_code = dto.coupon_code;
        self.delivery_carrier_id = dto.delivery_carrier_id;
        self.placed_at = dto.placed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Cart here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
