//! CheckoutSession DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CheckoutSession;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::StorefrontCheckoutState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CheckoutSession
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCheckoutSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cart_id")]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_order_id")]
    pub sales_order_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "gateway_transaction_id")]
    pub gateway_transaction_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "provider_code")]
    pub provider_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "provider_reference")]
    pub provider_reference: Option<String>,
    #[serde(alias = "amount_total")]
    pub amount_total: Decimal,
    pub state: StorefrontCheckoutState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "placed_at")]
    pub placed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "settled_at")]
    pub settled_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CheckoutSession
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCheckoutSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cart_id")]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_order_id")]
    pub sales_order_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "gateway_transaction_id")]
    pub gateway_transaction_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "provider_code")]
    pub provider_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "provider_reference")]
    pub provider_reference: Option<String>,
    #[serde(alias = "amount_total")]
    pub amount_total: Decimal,
    pub state: StorefrontCheckoutState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "placed_at")]
    pub placed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "settled_at")]
    pub settled_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CheckoutSession
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCheckoutSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cart_id")]
    pub cart_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_order_id")]
    pub sales_order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "gateway_transaction_id")]
    pub gateway_transaction_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "provider_code")]
    pub provider_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "provider_reference")]
    pub provider_reference: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "amount_total")]
    pub amount_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<StorefrontCheckoutState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "placed_at")]
    pub placed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "settled_at")]
    pub settled_at: Option<DateTime<Utc>>,
}

impl PatchCheckoutSessionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.cart_id.is_some() || self.website_id.is_some() || self.sales_order_id.is_some() || self.gateway_transaction_id.is_some() || self.provider_code.is_some() || self.provider_reference.is_some() || self.amount_total.is_some() || self.state.is_some() || self.placed_at.is_some() || self.settled_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CheckoutSession entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CheckoutSessionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    pub sales_order_id: Option<Uuid>,
    pub gateway_transaction_id: Option<Uuid>,
    pub provider_code: Option<String>,
    pub provider_reference: Option<String>,
    pub amount_total: Decimal,
    pub state: StorefrontCheckoutState,
    pub placed_at: Option<DateTime<Utc>>,
    pub settled_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CheckoutSession entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CheckoutSessionListResponseDto {
    /// List of items
    pub items: Vec<CheckoutSessionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CheckoutSessionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CheckoutSessionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CheckoutSessionSummaryDto {
    pub id: Uuid,
    pub cart_id: Uuid,
    pub website_id: Uuid,
    pub sales_order_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CheckoutSession> for CheckoutSessionResponseDto {
    fn from(entity: CheckoutSession) -> Self {
        Self {
            id: entity.id,
            cart_id: entity.cart_id,
            website_id: entity.website_id,
            sales_order_id: entity.sales_order_id,
            gateway_transaction_id: entity.gateway_transaction_id,
            provider_code: entity.provider_code,
            provider_reference: entity.provider_reference,
            amount_total: entity.amount_total,
            state: entity.state,
            placed_at: entity.placed_at,
            settled_at: entity.settled_at,
            metadata: entity.metadata,
        }
    }
}

impl From<CheckoutSession> for CheckoutSessionSummaryDto {
    fn from(entity: CheckoutSession) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            cart_id: entity.cart_id,
            website_id: entity.website_id,
            sales_order_id: entity.sales_order_id,
            created_at,
        }
    }
}

impl From<CreateCheckoutSessionDto> for CheckoutSession {
    fn from(dto: CreateCheckoutSessionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            cart_id: dto.cart_id,
            website_id: dto.website_id,
            sales_order_id: dto.sales_order_id,
            gateway_transaction_id: dto.gateway_transaction_id,
            provider_code: dto.provider_code,
            provider_reference: dto.provider_reference,
            amount_total: dto.amount_total,
            state: dto.state,
            placed_at: dto.placed_at,
            settled_at: dto.settled_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CheckoutSession> for CheckoutSessionResponseDto {
    fn from(entity: &CheckoutSession) -> Self {
        Self {
            id: entity.id.clone(),
            cart_id: entity.cart_id.clone(),
            website_id: entity.website_id.clone(),
            sales_order_id: entity.sales_order_id.clone(),
            gateway_transaction_id: entity.gateway_transaction_id.clone(),
            provider_code: entity.provider_code.clone(),
            provider_reference: entity.provider_reference.clone(),
            amount_total: entity.amount_total.clone(),
            state: entity.state.clone(),
            placed_at: entity.placed_at.clone(),
            settled_at: entity.settled_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCheckoutSessionDto> for CheckoutSession {
    fn from_create_dto(dto: CreateCheckoutSessionDto) -> backbone_core::ServiceResult<Self> {
        Ok(CheckoutSession::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCheckoutSessionDto> for CheckoutSession {
    fn apply_update(mut self, dto: UpdateCheckoutSessionDto) -> backbone_core::ServiceResult<Self> {
        self.cart_id = dto.cart_id;
        self.website_id = dto.website_id;
        self.sales_order_id = dto.sales_order_id;
        self.gateway_transaction_id = dto.gateway_transaction_id;
        self.provider_code = dto.provider_code;
        self.provider_reference = dto.provider_reference;
        self.amount_total = dto.amount_total;
        self.state = dto.state;
        self.placed_at = dto.placed_at;
        self.settled_at = dto.settled_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CheckoutSession here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
