//! DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod cart_dto;
pub mod cart_line_dto;
pub mod checkout_session_dto;
pub mod product_listing_dto;
pub mod product_price_dto;
pub mod recovery_invite_dto;
pub mod shopper_party_dto;
pub mod storefront_audit_log_dto;
pub mod website_sale_setting_dto;

// Re-exports
pub use cart_dto::{
    CreateCartDto,
    UpdateCartDto,
    PatchCartDto,
    CartResponseDto,
    CartListResponseDto,
    CartSummaryDto,
};
pub use cart_line_dto::{
    CreateCartLineDto,
    UpdateCartLineDto,
    PatchCartLineDto,
    CartLineResponseDto,
    CartLineListResponseDto,
    CartLineSummaryDto,
};
pub use checkout_session_dto::{
    CreateCheckoutSessionDto,
    UpdateCheckoutSessionDto,
    PatchCheckoutSessionDto,
    CheckoutSessionResponseDto,
    CheckoutSessionListResponseDto,
    CheckoutSessionSummaryDto,
};
pub use product_listing_dto::{
    CreateProductListingDto,
    UpdateProductListingDto,
    PatchProductListingDto,
    ProductListingResponseDto,
    ProductListingListResponseDto,
    ProductListingSummaryDto,
};
pub use product_price_dto::{
    CreateProductPriceDto,
    UpdateProductPriceDto,
    PatchProductPriceDto,
    ProductPriceResponseDto,
    ProductPriceListResponseDto,
    ProductPriceSummaryDto,
};
pub use recovery_invite_dto::{
    CreateRecoveryInviteDto,
    UpdateRecoveryInviteDto,
    PatchRecoveryInviteDto,
    RecoveryInviteResponseDto,
    RecoveryInviteListResponseDto,
    RecoveryInviteSummaryDto,
};
pub use shopper_party_dto::{
    CreateShopperPartyDto,
    UpdateShopperPartyDto,
    PatchShopperPartyDto,
    ShopperPartyResponseDto,
    ShopperPartyListResponseDto,
    ShopperPartySummaryDto,
};
pub use storefront_audit_log_dto::{
    CreateStorefrontAuditLogDto,
    UpdateStorefrontAuditLogDto,
    PatchStorefrontAuditLogDto,
    StorefrontAuditLogResponseDto,
    StorefrontAuditLogListResponseDto,
    StorefrontAuditLogSummaryDto,
};
pub use website_sale_setting_dto::{
    CreateWebsiteSaleSettingDto,
    UpdateWebsiteSaleSettingDto,
    PatchWebsiteSaleSettingDto,
    WebsiteSaleSettingResponseDto,
    WebsiteSaleSettingListResponseDto,
    WebsiteSaleSettingSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
