//! PickupLocation DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PickupLocation;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PickupLocation
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePickupLocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "address_line1")]
    pub address_line1: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opening_hours")]
    pub opening_hours: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PickupLocation
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePickupLocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "address_line1")]
    pub address_line1: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opening_hours")]
    pub opening_hours: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PickupLocation
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPickupLocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "address_line1")]
    pub address_line1: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "opening_hours")]
    pub opening_hours: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchPickupLocationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.warehouse_id.is_some() || self.name.is_some() || self.address_line1.is_some() || self.city.is_some() || self.postal_code.is_some() || self.country.is_some() || self.latitude.is_some() || self.longitude.is_some() || self.opening_hours.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PickupLocation entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PickupLocationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub address_line1: Option<String>,
    pub city: Option<String>,
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub opening_hours: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PickupLocation entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PickupLocationListResponseDto {
    /// List of items
    pub items: Vec<PickupLocationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PickupLocationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PickupLocationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PickupLocationSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub warehouse_id: Option<Uuid>,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PickupLocation> for PickupLocationResponseDto {
    fn from(entity: PickupLocation) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            warehouse_id: entity.warehouse_id,
            name: entity.name,
            address_line1: entity.address_line1,
            city: entity.city,
            postal_code: entity.postal_code,
            country: entity.country,
            latitude: entity.latitude,
            longitude: entity.longitude,
            opening_hours: entity.opening_hours,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<PickupLocation> for PickupLocationSummaryDto {
    fn from(entity: PickupLocation) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            warehouse_id: entity.warehouse_id,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreatePickupLocationDto> for PickupLocation {
    fn from(dto: CreatePickupLocationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            warehouse_id: dto.warehouse_id,
            name: dto.name,
            address_line1: dto.address_line1,
            city: dto.city,
            postal_code: dto.postal_code,
            country: dto.country,
            latitude: dto.latitude,
            longitude: dto.longitude,
            opening_hours: dto.opening_hours,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PickupLocation> for PickupLocationResponseDto {
    fn from(entity: &PickupLocation) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            warehouse_id: entity.warehouse_id.clone(),
            name: entity.name.clone(),
            address_line1: entity.address_line1.clone(),
            city: entity.city.clone(),
            postal_code: entity.postal_code.clone(),
            country: entity.country.clone(),
            latitude: entity.latitude.clone(),
            longitude: entity.longitude.clone(),
            opening_hours: entity.opening_hours.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePickupLocationDto> for PickupLocation {
    fn from_create_dto(dto: CreatePickupLocationDto) -> backbone_core::ServiceResult<Self> {
        Ok(PickupLocation::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePickupLocationDto> for PickupLocation {
    fn apply_update(mut self, dto: UpdatePickupLocationDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.warehouse_id = dto.warehouse_id;
        self.name = dto.name;
        self.address_line1 = dto.address_line1;
        self.city = dto.city;
        self.postal_code = dto.postal_code;
        self.country = dto.country;
        self.latitude = dto.latitude;
        self.longitude = dto.longitude;
        self.opening_hours = dto.opening_hours;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PickupLocation here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

