//! ProductPrice DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ProductPrice;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ProductPrice
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateProductPriceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[serde(alias = "list_price")]
    pub list_price: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "compare_at_price")]
    pub compare_at_price: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ProductPrice
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateProductPriceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[serde(alias = "list_price")]
    pub list_price: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "compare_at_price")]
    pub compare_at_price: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ProductPrice
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchProductPriceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "list_price")]
    pub list_price: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "compare_at_price")]
    pub compare_at_price: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}

impl PatchProductPriceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.item_id.is_some() || self.list_price.is_some() || self.compare_at_price.is_some() || self.currency.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ProductPrice entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductPriceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub list_price: Decimal,
    pub compare_at_price: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ProductPrice entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductPriceListResponseDto {
    /// List of items
    pub items: Vec<ProductPriceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ProductPriceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ProductPriceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductPriceSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub item_id: Uuid,
    pub list_price: Decimal,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ProductPrice> for ProductPriceResponseDto {
    fn from(entity: ProductPrice) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            item_id: entity.item_id,
            list_price: entity.list_price,
            compare_at_price: entity.compare_at_price,
            currency: entity.currency,
            metadata: entity.metadata,
        }
    }
}

impl From<ProductPrice> for ProductPriceSummaryDto {
    fn from(entity: ProductPrice) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            item_id: entity.item_id,
            list_price: entity.list_price,
            created_at,
        }
    }
}

impl From<CreateProductPriceDto> for ProductPrice {
    fn from(dto: CreateProductPriceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            item_id: dto.item_id,
            list_price: dto.list_price,
            compare_at_price: dto.compare_at_price,
            currency: dto.currency,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ProductPrice> for ProductPriceResponseDto {
    fn from(entity: &ProductPrice) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            item_id: entity.item_id.clone(),
            list_price: entity.list_price.clone(),
            compare_at_price: entity.compare_at_price.clone(),
            currency: entity.currency.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateProductPriceDto> for ProductPrice {
    fn from_create_dto(dto: CreateProductPriceDto) -> backbone_core::ServiceResult<Self> {
        Ok(ProductPrice::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateProductPriceDto> for ProductPrice {
    fn apply_update(mut self, dto: UpdateProductPriceDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.item_id = dto.item_id;
        self.list_price = dto.list_price;
        self.compare_at_price = dto.compare_at_price;
        self.currency = dto.currency;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ProductPrice here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
