//! ProductListing DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ProductListing;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ProductListing
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateProductListingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "sale_ok")]
    pub sale_ok: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_published")]
    pub is_published: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(alias = "media_urls")]
    pub media_urls: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ProductListing
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateProductListingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "sale_ok")]
    pub sale_ok: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_published")]
    pub is_published: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(alias = "media_urls")]
    pub media_urls: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ProductListing
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchProductListingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sale_ok")]
    pub sale_ok: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_published")]
    pub is_published: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "media_urls")]
    pub media_urls: Option<serde_json::Value>,
}

impl PatchProductListingDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.item_id.is_some() || self.sale_ok.is_some() || self.is_published.is_some() || self.sequence.is_some() || self.media_urls.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ProductListing entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductListingResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub sale_ok: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_published: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub media_urls: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ProductListing entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductListingListResponseDto {
    /// List of items
    pub items: Vec<ProductListingResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ProductListingListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ProductListingResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductListingSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub item_id: Uuid,
    pub sale_ok: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ProductListing> for ProductListingResponseDto {
    fn from(entity: ProductListing) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            item_id: entity.item_id,
            sale_ok: entity.sale_ok,
            is_published: entity.is_published,
            sequence: entity.sequence,
            media_urls: entity.media_urls,
            metadata: entity.metadata,
        }
    }
}

impl From<ProductListing> for ProductListingSummaryDto {
    fn from(entity: ProductListing) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            item_id: entity.item_id,
            sale_ok: entity.sale_ok,
            created_at,
        }
    }
}

impl From<CreateProductListingDto> for ProductListing {
    fn from(dto: CreateProductListingDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            item_id: dto.item_id,
            sale_ok: dto.sale_ok,
            is_published: dto.is_published,
            sequence: dto.sequence,
            media_urls: dto.media_urls,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ProductListing> for ProductListingResponseDto {
    fn from(entity: &ProductListing) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            item_id: entity.item_id.clone(),
            sale_ok: entity.sale_ok.clone(),
            is_published: entity.is_published.clone(),
            sequence: entity.sequence.clone(),
            media_urls: entity.media_urls.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateProductListingDto> for ProductListing {
    fn from_create_dto(dto: CreateProductListingDto) -> backbone_core::ServiceResult<Self> {
        Ok(ProductListing::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateProductListingDto> for ProductListing {
    fn apply_update(mut self, dto: UpdateProductListingDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.item_id = dto.item_id;
        self.sale_ok = dto.sale_ok;
        self.is_published = dto.is_published;
        self.sequence = dto.sequence;
        self.media_urls = dto.media_urls;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ProductListing here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
