//! RecoveryInvite DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::RecoveryInvite;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new RecoveryInvite
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRecoveryInviteDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cart_id")]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "template_ref")]
    pub template_ref: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "notified_at")]
    pub notified_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "delivery_state")]
    pub delivery_state: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a RecoveryInvite
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRecoveryInviteDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cart_id")]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "template_ref")]
    pub template_ref: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "notified_at")]
    pub notified_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "delivery_state")]
    pub delivery_state: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a RecoveryInvite
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRecoveryInviteDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cart_id")]
    pub cart_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_ref")]
    pub template_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "notified_at")]
    pub notified_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "delivery_state")]
    pub delivery_state: Option<String>,
}

impl PatchRecoveryInviteDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.cart_id.is_some() || self.template_ref.is_some() || self.notified_at.is_some() || self.delivery_state.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for RecoveryInvite entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RecoveryInviteResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub cart_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub template_ref: String,
    pub notified_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub delivery_state: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for RecoveryInvite entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RecoveryInviteListResponseDto {
    /// List of items
    pub items: Vec<RecoveryInviteResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RecoveryInviteListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RecoveryInviteResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RecoveryInviteSummaryDto {
    pub id: Uuid,
    pub cart_id: Uuid,
    pub template_ref: String,
    pub notified_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<RecoveryInvite> for RecoveryInviteResponseDto {
    fn from(entity: RecoveryInvite) -> Self {
        Self {
            id: entity.id,
            cart_id: entity.cart_id,
            template_ref: entity.template_ref,
            notified_at: entity.notified_at,
            delivery_state: entity.delivery_state,
            metadata: entity.metadata,
        }
    }
}

impl From<RecoveryInvite> for RecoveryInviteSummaryDto {
    fn from(entity: RecoveryInvite) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            cart_id: entity.cart_id,
            template_ref: entity.template_ref,
            notified_at: entity.notified_at,
            created_at,
        }
    }
}

impl From<CreateRecoveryInviteDto> for RecoveryInvite {
    fn from(dto: CreateRecoveryInviteDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            cart_id: dto.cart_id,
            template_ref: dto.template_ref,
            notified_at: dto.notified_at,
            delivery_state: dto.delivery_state,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&RecoveryInvite> for RecoveryInviteResponseDto {
    fn from(entity: &RecoveryInvite) -> Self {
        Self {
            id: entity.id.clone(),
            cart_id: entity.cart_id.clone(),
            template_ref: entity.template_ref.clone(),
            notified_at: entity.notified_at.clone(),
            delivery_state: entity.delivery_state.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRecoveryInviteDto> for RecoveryInvite {
    fn from_create_dto(dto: CreateRecoveryInviteDto) -> backbone_core::ServiceResult<Self> {
        Ok(RecoveryInvite::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRecoveryInviteDto> for RecoveryInvite {
    fn apply_update(mut self, dto: UpdateRecoveryInviteDto) -> backbone_core::ServiceResult<Self> {
        self.cart_id = dto.cart_id;
        self.template_ref = dto.template_ref;
        self.notified_at = dto.notified_at;
        self.delivery_state = dto.delivery_state;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to RecoveryInvite here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
