//! ShopperParty DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ShopperParty;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ShopperParty
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateShopperPartyDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "email_normalized")]
    pub email_normalized: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ShopperParty
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateShopperPartyDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "email_normalized")]
    pub email_normalized: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ShopperParty
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchShopperPartyDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "email_normalized")]
    pub email_normalized: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
}

impl PatchShopperPartyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.email_normalized.is_some() || self.party_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ShopperParty entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ShopperPartyResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email_normalized: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub party_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ShopperParty entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ShopperPartyListResponseDto {
    /// List of items
    pub items: Vec<ShopperPartyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ShopperPartyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ShopperPartyResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ShopperPartySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub email_normalized: String,
    pub party_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ShopperParty> for ShopperPartyResponseDto {
    fn from(entity: ShopperParty) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            email_normalized: entity.email_normalized,
            party_id: entity.party_id,
            metadata: entity.metadata,
        }
    }
}

impl From<ShopperParty> for ShopperPartySummaryDto {
    fn from(entity: ShopperParty) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            email_normalized: entity.email_normalized,
            party_id: entity.party_id,
            created_at,
        }
    }
}

impl From<CreateShopperPartyDto> for ShopperParty {
    fn from(dto: CreateShopperPartyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            email_normalized: dto.email_normalized,
            party_id: dto.party_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ShopperParty> for ShopperPartyResponseDto {
    fn from(entity: &ShopperParty) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            email_normalized: entity.email_normalized.clone(),
            party_id: entity.party_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateShopperPartyDto> for ShopperParty {
    fn from_create_dto(dto: CreateShopperPartyDto) -> backbone_core::ServiceResult<Self> {
        Ok(ShopperParty::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateShopperPartyDto> for ShopperParty {
    fn apply_update(mut self, dto: UpdateShopperPartyDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.email_normalized = dto.email_normalized;
        self.party_id = dto.party_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ShopperParty here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
