//! StorefrontAuditLog DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::StorefrontAuditLog;
use crate::domain::entity::StorefrontAuditEvent;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new StorefrontAuditLog
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateStorefrontAuditLogDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    pub event: StorefrontAuditEvent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a StorefrontAuditLog
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateStorefrontAuditLogDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    pub event: StorefrontAuditEvent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a StorefrontAuditLog
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchStorefrontAuditLogDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event: Option<StorefrontAuditEvent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "occurred_at")]
    pub occurred_at: Option<DateTime<Utc>>,
}

impl PatchStorefrontAuditLogDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.event.is_some() || self.actor.is_some() || self.subject_type.is_some() || self.subject_id.is_some() || self.detail.is_some() || self.occurred_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for StorefrontAuditLog entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StorefrontAuditLogResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub website_id: Option<Uuid>,
    pub event: StorefrontAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for StorefrontAuditLog entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StorefrontAuditLogListResponseDto {
    /// List of items
    pub items: Vec<StorefrontAuditLogResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl StorefrontAuditLogListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<StorefrontAuditLogResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StorefrontAuditLogSummaryDto {
    pub id: Uuid,
    pub website_id: Option<Uuid>,
    pub event: StorefrontAuditEvent,
    pub actor: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<StorefrontAuditLog> for StorefrontAuditLogResponseDto {
    fn from(entity: StorefrontAuditLog) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            event: entity.event,
            actor: entity.actor,
            subject_type: entity.subject_type,
            subject_id: entity.subject_id,
            detail: entity.detail,
            occurred_at: entity.occurred_at,
        }
    }
}

impl From<StorefrontAuditLog> for StorefrontAuditLogSummaryDto {
    fn from(entity: StorefrontAuditLog) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            event: entity.event,
            actor: entity.actor,
            created_at,
        }
    }
}

impl From<CreateStorefrontAuditLogDto> for StorefrontAuditLog {
    fn from(dto: CreateStorefrontAuditLogDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            event: dto.event,
            actor: dto.actor,
            subject_type: dto.subject_type,
            subject_id: dto.subject_id,
            detail: dto.detail,
            occurred_at: dto.occurred_at,
        }
    }
}

impl From<&StorefrontAuditLog> for StorefrontAuditLogResponseDto {
    fn from(entity: &StorefrontAuditLog) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            event: entity.event.clone(),
            actor: entity.actor.clone(),
            subject_type: entity.subject_type.clone(),
            subject_id: entity.subject_id.clone(),
            detail: entity.detail.clone(),
            occurred_at: entity.occurred_at.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateStorefrontAuditLogDto> for StorefrontAuditLog {
    fn from_create_dto(dto: CreateStorefrontAuditLogDto) -> backbone_core::ServiceResult<Self> {
        Ok(StorefrontAuditLog::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateStorefrontAuditLogDto> for StorefrontAuditLog {
    fn apply_update(mut self, dto: UpdateStorefrontAuditLogDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.event = dto.event;
        self.actor = dto.actor;
        self.subject_type = dto.subject_type;
        self.subject_id = dto.subject_id;
        self.detail = dto.detail;
        self.occurred_at = dto.occurred_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to StorefrontAuditLog here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
