//! WebsiteSaleSetting DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::WebsiteSaleSetting;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::StorefrontAccessGate;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new WebsiteSaleSetting
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWebsiteSaleSettingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(alias = "access_gate")]
    pub access_gate: StorefrontAccessGate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "default_customer_group_id")]
    pub default_customer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "guest_party_id")]
    pub guest_party_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "recovery_template_ref")]
    pub recovery_template_ref: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a WebsiteSaleSetting
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWebsiteSaleSettingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[serde(alias = "access_gate")]
    pub access_gate: StorefrontAccessGate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "default_customer_group_id")]
    pub default_customer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "guest_party_id")]
    pub guest_party_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "recovery_template_ref")]
    pub recovery_template_ref: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a WebsiteSaleSetting
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWebsiteSaleSettingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "access_gate")]
    pub access_gate: Option<StorefrontAccessGate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_customer_group_id")]
    pub default_customer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "guest_party_id")]
    pub guest_party_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recovery_template_ref")]
    pub recovery_template_ref: Option<String>,
}

impl PatchWebsiteSaleSettingDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.access_gate.is_some() || self.default_customer_group_id.is_some() || self.guest_party_id.is_some() || self.recovery_template_ref.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for WebsiteSaleSetting entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteSaleSettingResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    pub access_gate: StorefrontAccessGate,
    pub default_customer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub guest_party_id: Uuid,
    pub recovery_template_ref: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for WebsiteSaleSetting entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteSaleSettingListResponseDto {
    /// List of items
    pub items: Vec<WebsiteSaleSettingResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WebsiteSaleSettingListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WebsiteSaleSettingResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebsiteSaleSettingSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub access_gate: StorefrontAccessGate,
    pub default_customer_group_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<WebsiteSaleSetting> for WebsiteSaleSettingResponseDto {
    fn from(entity: WebsiteSaleSetting) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            access_gate: entity.access_gate,
            default_customer_group_id: entity.default_customer_group_id,
            guest_party_id: entity.guest_party_id,
            recovery_template_ref: entity.recovery_template_ref,
            metadata: entity.metadata,
        }
    }
}

impl From<WebsiteSaleSetting> for WebsiteSaleSettingSummaryDto {
    fn from(entity: WebsiteSaleSetting) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            access_gate: entity.access_gate,
            default_customer_group_id: entity.default_customer_group_id,
            created_at,
        }
    }
}

impl From<CreateWebsiteSaleSettingDto> for WebsiteSaleSetting {
    fn from(dto: CreateWebsiteSaleSettingDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            access_gate: dto.access_gate,
            default_customer_group_id: dto.default_customer_group_id,
            guest_party_id: dto.guest_party_id,
            recovery_template_ref: dto.recovery_template_ref,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&WebsiteSaleSetting> for WebsiteSaleSettingResponseDto {
    fn from(entity: &WebsiteSaleSetting) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            access_gate: entity.access_gate.clone(),
            default_customer_group_id: entity.default_customer_group_id.clone(),
            guest_party_id: entity.guest_party_id.clone(),
            recovery_template_ref: entity.recovery_template_ref.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWebsiteSaleSettingDto> for WebsiteSaleSetting {
    fn from_create_dto(dto: CreateWebsiteSaleSettingDto) -> backbone_core::ServiceResult<Self> {
        Ok(WebsiteSaleSetting::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWebsiteSaleSettingDto> for WebsiteSaleSetting {
    fn apply_update(mut self, dto: UpdateWebsiteSaleSettingDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.access_gate = dto.access_gate;
        self.default_customer_group_id = dto.default_customer_group_id;
        self.guest_party_id = dto.guest_party_id;
        self.recovery_template_ref = dto.recovery_template_ref;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to WebsiteSaleSetting here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
