//! WishlistItem DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::WishlistItem;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new WishlistItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWishlistItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "visitor_id")]
    pub visitor_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "notify_on_stock")]
    pub notify_on_stock: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "contact_email")]
    pub contact_email: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a WishlistItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWishlistItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "visitor_id")]
    pub visitor_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "notify_on_stock")]
    pub notify_on_stock: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "contact_email")]
    pub contact_email: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a WishlistItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWishlistItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_id")]
    pub visitor_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "portal_user_id")]
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "notify_on_stock")]
    pub notify_on_stock: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "contact_email")]
    pub contact_email: Option<String>,
}

impl PatchWishlistItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.website_id.is_some() || self.visitor_id.is_some() || self.portal_user_id.is_some() || self.item_id.is_some() || self.notify_on_stock.is_some() || self.contact_email.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for WishlistItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WishlistItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub visitor_id: Uuid,
    pub portal_user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub notify_on_stock: bool,
    pub contact_email: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for WishlistItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WishlistItemListResponseDto {
    /// List of items
    pub items: Vec<WishlistItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WishlistItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WishlistItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WishlistItemSummaryDto {
    pub id: Uuid,
    pub website_id: Uuid,
    pub visitor_id: Uuid,
    pub portal_user_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<WishlistItem> for WishlistItemResponseDto {
    fn from(entity: WishlistItem) -> Self {
        Self {
            id: entity.id,
            website_id: entity.website_id,
            visitor_id: entity.visitor_id,
            portal_user_id: entity.portal_user_id,
            item_id: entity.item_id,
            notify_on_stock: entity.notify_on_stock,
            contact_email: entity.contact_email,
            metadata: entity.metadata,
        }
    }
}

impl From<WishlistItem> for WishlistItemSummaryDto {
    fn from(entity: WishlistItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            website_id: entity.website_id,
            visitor_id: entity.visitor_id,
            portal_user_id: entity.portal_user_id,
            created_at,
        }
    }
}

impl From<CreateWishlistItemDto> for WishlistItem {
    fn from(dto: CreateWishlistItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            website_id: dto.website_id,
            visitor_id: dto.visitor_id,
            portal_user_id: dto.portal_user_id,
            item_id: dto.item_id,
            notify_on_stock: dto.notify_on_stock,
            contact_email: dto.contact_email,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&WishlistItem> for WishlistItemResponseDto {
    fn from(entity: &WishlistItem) -> Self {
        Self {
            id: entity.id.clone(),
            website_id: entity.website_id.clone(),
            visitor_id: entity.visitor_id.clone(),
            portal_user_id: entity.portal_user_id.clone(),
            item_id: entity.item_id.clone(),
            notify_on_stock: entity.notify_on_stock.clone(),
            contact_email: entity.contact_email.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWishlistItemDto> for WishlistItem {
    fn from_create_dto(dto: CreateWishlistItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(WishlistItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWishlistItemDto> for WishlistItem {
    fn apply_update(mut self, dto: UpdateWishlistItemDto) -> backbone_core::ServiceResult<Self> {
        self.website_id = dto.website_id;
        self.visitor_id = dto.visitor_id;
        self.portal_user_id = dto.portal_user_id;
        self.item_id = dto.item_id;
        self.notify_on_stock = dto.notify_on_stock;
        self.contact_email = dto.contact_email;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to WishlistItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

