//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod cart_specification;
pub mod cart_line_specification;
pub mod checkout_session_specification;
pub mod product_listing_specification;
pub mod product_price_specification;
pub mod recovery_invite_specification;
pub mod shopper_party_specification;
pub mod storefront_audit_log_specification;
pub mod website_sale_setting_specification;

// <<< CUSTOM
// END CUSTOM
