//! Application service for PickupLocation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `pickup_location_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePickupLocationDto, UpdatePickupLocationDto};
use crate::domain::entity::PickupLocation;
use crate::infrastructure::persistence::PickupLocationRepository;

/// Application service for PickupLocation entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `pickup_location_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PickupLocationServiceCustom {
///     inner: Arc<PickupLocationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PickupLocationService = GenericCrudService<
    PickupLocation,
    CreatePickupLocationDto,
    UpdatePickupLocationDto,
    PickupLocationRepository,
>;

// <<< CUSTOM
// END CUSTOM
