//! Application service for ProductListing entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `product_listing_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateProductListingDto, UpdateProductListingDto};
use crate::domain::entity::ProductListing;
use crate::infrastructure::persistence::ProductListingRepository;

/// Application service for ProductListing entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `product_listing_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ProductListingServiceCustom {
///     inner: Arc<ProductListingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ProductListingService = GenericCrudService<
    ProductListing,
    CreateProductListingDto,
    UpdateProductListingDto,
    ProductListingRepository,
>;

// <<< CUSTOM
// END CUSTOM
