//! Application service for ShopperParty entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `shopper_party_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateShopperPartyDto, UpdateShopperPartyDto};
use crate::domain::entity::ShopperParty;
use crate::infrastructure::persistence::ShopperPartyRepository;

/// Application service for ShopperParty entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `shopper_party_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ShopperPartyServiceCustom {
///     inner: Arc<ShopperPartyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ShopperPartyService = GenericCrudService<
    ShopperParty,
    CreateShopperPartyDto,
    UpdateShopperPartyDto,
    ShopperPartyRepository,
>;

// <<< CUSTOM
// END CUSTOM
