//! Application service for StorefrontAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `storefront_audit_log_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateStorefrontAuditLogDto, UpdateStorefrontAuditLogDto};
use crate::domain::entity::StorefrontAuditLog;
use crate::infrastructure::persistence::StorefrontAuditLogRepository;

/// Application service for StorefrontAuditLog entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `storefront_audit_log_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct StorefrontAuditLogServiceCustom {
///     inner: Arc<StorefrontAuditLogService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type StorefrontAuditLogService = GenericCrudService<
    StorefrontAuditLog,
    CreateStorefrontAuditLogDto,
    UpdateStorefrontAuditLogDto,
    StorefrontAuditLogRepository,
>;

// <<< CUSTOM
// END CUSTOM
