//! Application service for WebsiteSaleSetting entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `website_sale_setting_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWebsiteSaleSettingDto, UpdateWebsiteSaleSettingDto};
use crate::domain::entity::WebsiteSaleSetting;
use crate::infrastructure::persistence::WebsiteSaleSettingRepository;

/// Application service for WebsiteSaleSetting entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `website_sale_setting_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WebsiteSaleSettingServiceCustom {
///     inner: Arc<WebsiteSaleSettingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WebsiteSaleSettingService = GenericCrudService<
    WebsiteSaleSetting,
    CreateWebsiteSaleSettingDto,
    UpdateWebsiteSaleSettingDto,
    WebsiteSaleSettingRepository,
>;

// <<< CUSTOM
// END CUSTOM
