//! Application service for WishlistItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `wishlist_item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWishlistItemDto, UpdateWishlistItemDto};
use crate::domain::entity::WishlistItem;
use crate::infrastructure::persistence::WishlistItemRepository;

/// Application service for WishlistItem entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `wishlist_item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WishlistItemServiceCustom {
///     inner: Arc<WishlistItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WishlistItemService = GenericCrudService<
    WishlistItem,
    CreateWishlistItemDto,
    UpdateWishlistItemDto,
    WishlistItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
