-- Cart Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.carts table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.carts (
--     id,
--     website_id,
--     visitor_id,
--     portal_user_id,
--     party_id,
--     state,
--     coupon_code,
--     delivery_carrier_id,
--     placed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.carts (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

