-- CartLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.cart_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.cart_lines (
--     id,
--     cart_id,
--     item_id,
--     quantity,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.cart_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

