-- CheckoutSession Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.checkout_sessions table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.checkout_sessions (
--     id,
--     cart_id,
--     website_id,
--     sales_order_id,
--     gateway_transaction_id,
--     provider_code,
--     provider_reference,
--     amount_total,
--     state,
--     placed_at,
--     settled_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.checkout_sessions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

