-- ProductPrice Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.product_prices table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.product_prices (
--     id,
--     website_id,
--     item_id,
--     list_price,
--     compare_at_price,
--     currency,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.product_prices (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

