-- RecoveryInvite Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.recovery_invites table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.recovery_invites (
--     id,
--     cart_id,
--     template_ref,
--     notified_at,
--     delivery_state,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.recovery_invites (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

