-- ShopperParty Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.shopper_parties table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.shopper_parties (
--     id,
--     company_id,
--     email_normalized,
--     party_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.shopper_parties (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

