-- StorefrontAuditLog Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.storefront_audit_log table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.storefront_audit_log (
--     id,
--     website_id,
--     event,
--     actor,
--     subject_type,
--     subject_id,
--     detail,
--     occurred_at
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.storefront_audit_log (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

