-- WebsiteSaleSetting Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the storefront.website_sale_settings table.
-- Customize this file to add your initial data.

-- INSERT INTO storefront.website_sale_settings (
--     id,
--     website_id,
--     access_gate,
--     default_customer_group_id,
--     guest_party_id,
--     recovery_template_ref,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO storefront.website_sale_settings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

