-- Migration: storefront audit triggers — created_at/updated_at stamping
-- (the portal add_audit_triggers shape, consolidated by hand from the
-- generator's output). One function + insert/update trigger pair per table;
-- idempotent (DROP IF EXISTS before every CREATE).

-- Audit Triggers Migration for storefront module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Cart (storefront.carts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.carts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS carts_insert_audit ON storefront.carts;
CREATE TRIGGER carts_insert_audit BEFORE INSERT ON storefront.carts
    FOR EACH ROW EXECUTE FUNCTION storefront.carts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS carts_update_audit ON storefront.carts;
CREATE TRIGGER carts_update_audit BEFORE UPDATE ON storefront.carts
    FOR EACH ROW EXECUTE FUNCTION storefront.carts_audit_timestamp();

-- ==============================================================================
-- Table: CartLine (storefront.cart_lines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.cart_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS cart_lines_insert_audit ON storefront.cart_lines;
CREATE TRIGGER cart_lines_insert_audit BEFORE INSERT ON storefront.cart_lines
    FOR EACH ROW EXECUTE FUNCTION storefront.cart_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS cart_lines_update_audit ON storefront.cart_lines;
CREATE TRIGGER cart_lines_update_audit BEFORE UPDATE ON storefront.cart_lines
    FOR EACH ROW EXECUTE FUNCTION storefront.cart_lines_audit_timestamp();

-- ==============================================================================
-- Table: CheckoutSession (storefront.checkout_sessions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.checkout_sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS checkout_sessions_insert_audit ON storefront.checkout_sessions;
CREATE TRIGGER checkout_sessions_insert_audit BEFORE INSERT ON storefront.checkout_sessions
    FOR EACH ROW EXECUTE FUNCTION storefront.checkout_sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS checkout_sessions_update_audit ON storefront.checkout_sessions;
CREATE TRIGGER checkout_sessions_update_audit BEFORE UPDATE ON storefront.checkout_sessions
    FOR EACH ROW EXECUTE FUNCTION storefront.checkout_sessions_audit_timestamp();

-- ==============================================================================
-- Table: ProductListing (storefront.product_listings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.product_listings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS product_listings_insert_audit ON storefront.product_listings;
CREATE TRIGGER product_listings_insert_audit BEFORE INSERT ON storefront.product_listings
    FOR EACH ROW EXECUTE FUNCTION storefront.product_listings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS product_listings_update_audit ON storefront.product_listings;
CREATE TRIGGER product_listings_update_audit BEFORE UPDATE ON storefront.product_listings
    FOR EACH ROW EXECUTE FUNCTION storefront.product_listings_audit_timestamp();

-- ==============================================================================
-- Table: ProductPrice (storefront.product_prices)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.product_prices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS product_prices_insert_audit ON storefront.product_prices;
CREATE TRIGGER product_prices_insert_audit BEFORE INSERT ON storefront.product_prices
    FOR EACH ROW EXECUTE FUNCTION storefront.product_prices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS product_prices_update_audit ON storefront.product_prices;
CREATE TRIGGER product_prices_update_audit BEFORE UPDATE ON storefront.product_prices
    FOR EACH ROW EXECUTE FUNCTION storefront.product_prices_audit_timestamp();

-- ==============================================================================
-- Table: RecoveryInvite (storefront.recovery_invites)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.recovery_invites_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS recovery_invites_insert_audit ON storefront.recovery_invites;
CREATE TRIGGER recovery_invites_insert_audit BEFORE INSERT ON storefront.recovery_invites
    FOR EACH ROW EXECUTE FUNCTION storefront.recovery_invites_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS recovery_invites_update_audit ON storefront.recovery_invites;
CREATE TRIGGER recovery_invites_update_audit BEFORE UPDATE ON storefront.recovery_invites
    FOR EACH ROW EXECUTE FUNCTION storefront.recovery_invites_audit_timestamp();

-- ==============================================================================
-- Table: ShopperParty (storefront.shopper_parties)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.shopper_parties_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS shopper_parties_insert_audit ON storefront.shopper_parties;
CREATE TRIGGER shopper_parties_insert_audit BEFORE INSERT ON storefront.shopper_parties
    FOR EACH ROW EXECUTE FUNCTION storefront.shopper_parties_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS shopper_parties_update_audit ON storefront.shopper_parties;
CREATE TRIGGER shopper_parties_update_audit BEFORE UPDATE ON storefront.shopper_parties
    FOR EACH ROW EXECUTE FUNCTION storefront.shopper_parties_audit_timestamp();

-- ==============================================================================
-- Table: WebsiteSaleSetting (storefront.website_sale_settings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION storefront.website_sale_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS website_sale_settings_insert_audit ON storefront.website_sale_settings;
CREATE TRIGGER website_sale_settings_insert_audit BEFORE INSERT ON storefront.website_sale_settings
    FOR EACH ROW EXECUTE FUNCTION storefront.website_sale_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS website_sale_settings_update_audit ON storefront.website_sale_settings;
CREATE TRIGGER website_sale_settings_update_audit BEFORE UPDATE ON storefront.website_sale_settings
    FOR EACH ROW EXECUTE FUNCTION storefront.website_sale_settings_audit_timestamp();

