//! Event handler trait for CartLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CartLineEvent;

/// Event handler for CartLine events.
/// Implement this trait to react to CartLine lifecycle events.
pub trait CartLineEventHandler: EventHandler<CartLineEvent> {}
