//! Domain events for Cart entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Cart;

/// Domain events for Cart — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Cart>)` variant.
pub type CartEvent = CrudEvent<Cart>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Cart events.
pub type CartEventPublisher = Arc<dyn CrudEventPublisher<Cart> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCartEventPublisher = NoOpCrudEventPublisher<Cart>;
