//! Event handler trait for Cart events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CartEvent;

/// Event handler for Cart events.
/// Implement this trait to react to Cart lifecycle events.
pub trait CartEventHandler: EventHandler<CartEvent> {}
