//! Domain events for CartLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CartLine;

/// Domain events for CartLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CartLine>)` variant.
pub type CartLineEvent = CrudEvent<CartLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CartLine events.
pub type CartLineEventPublisher = Arc<dyn CrudEventPublisher<CartLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCartLineEventPublisher = NoOpCrudEventPublisher<CartLine>;
