//! Event handler trait for CheckoutSession events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CheckoutSessionEvent;

/// Event handler for CheckoutSession events.
/// Implement this trait to react to CheckoutSession lifecycle events.
pub trait CheckoutSessionEventHandler: EventHandler<CheckoutSessionEvent> {}
