//! Event handler trait for PickupLocation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PickupLocationEvent;

/// Event handler for PickupLocation events.
/// Implement this trait to react to PickupLocation lifecycle events.
pub trait PickupLocationEventHandler: EventHandler<PickupLocationEvent> {}
