//! Domain events for PickupLocation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PickupLocation;

/// Domain events for PickupLocation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PickupLocation>)` variant.
pub type PickupLocationEvent = CrudEvent<PickupLocation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PickupLocation events.
pub type PickupLocationEventPublisher = Arc<dyn CrudEventPublisher<PickupLocation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPickupLocationEventPublisher = NoOpCrudEventPublisher<PickupLocation>;
