//! Event handler trait for ProductListing events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProductListingEvent;

/// Event handler for ProductListing events.
/// Implement this trait to react to ProductListing lifecycle events.
pub trait ProductListingEventHandler: EventHandler<ProductListingEvent> {}
