//! Domain events for ProductListing entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ProductListing;

/// Domain events for ProductListing — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ProductListing>)` variant.
pub type ProductListingEvent = CrudEvent<ProductListing>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ProductListing events.
pub type ProductListingEventPublisher = Arc<dyn CrudEventPublisher<ProductListing> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopProductListingEventPublisher = NoOpCrudEventPublisher<ProductListing>;
