//! Event handler trait for ProductPrice events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProductPriceEvent;

/// Event handler for ProductPrice events.
/// Implement this trait to react to ProductPrice lifecycle events.
pub trait ProductPriceEventHandler: EventHandler<ProductPriceEvent> {}
