//! Domain events for ProductPrice entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ProductPrice;

/// Domain events for ProductPrice — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ProductPrice>)` variant.
pub type ProductPriceEvent = CrudEvent<ProductPrice>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ProductPrice events.
pub type ProductPriceEventPublisher = Arc<dyn CrudEventPublisher<ProductPrice> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopProductPriceEventPublisher = NoOpCrudEventPublisher<ProductPrice>;
