//! Domain events for RecoveryInvite entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RecoveryInvite;

/// Domain events for RecoveryInvite — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RecoveryInvite>)` variant.
pub type RecoveryInviteEvent = CrudEvent<RecoveryInvite>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RecoveryInvite events.
pub type RecoveryInviteEventPublisher = Arc<dyn CrudEventPublisher<RecoveryInvite> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRecoveryInviteEventPublisher = NoOpCrudEventPublisher<RecoveryInvite>;
