//! Event handler trait for RecoveryInvite events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RecoveryInviteEvent;

/// Event handler for RecoveryInvite events.
/// Implement this trait to react to RecoveryInvite lifecycle events.
pub trait RecoveryInviteEventHandler: EventHandler<RecoveryInviteEvent> {}
