//! Event handler trait for ShopperParty events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ShopperPartyEvent;

/// Event handler for ShopperParty events.
/// Implement this trait to react to ShopperParty lifecycle events.
pub trait ShopperPartyEventHandler: EventHandler<ShopperPartyEvent> {}
