//! Domain events for ShopperParty entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ShopperParty;

/// Domain events for ShopperParty — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ShopperParty>)` variant.
pub type ShopperPartyEvent = CrudEvent<ShopperParty>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ShopperParty events.
pub type ShopperPartyEventPublisher = Arc<dyn CrudEventPublisher<ShopperParty> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopShopperPartyEventPublisher = NoOpCrudEventPublisher<ShopperParty>;
