//! Event handler trait for StorefrontAuditLog events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::StorefrontAuditLogEvent;

/// Event handler for StorefrontAuditLog events.
/// Implement this trait to react to StorefrontAuditLog lifecycle events.
pub trait StorefrontAuditLogEventHandler: EventHandler<StorefrontAuditLogEvent> {}
