//! Domain events for StorefrontAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::StorefrontAuditLog;

/// Domain events for StorefrontAuditLog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<StorefrontAuditLog>)` variant.
pub type StorefrontAuditLogEvent = CrudEvent<StorefrontAuditLog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for StorefrontAuditLog events.
pub type StorefrontAuditLogEventPublisher = Arc<dyn CrudEventPublisher<StorefrontAuditLog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopStorefrontAuditLogEventPublisher = NoOpCrudEventPublisher<StorefrontAuditLog>;
