//! Domain events for WebsiteSaleSetting entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WebsiteSaleSetting;

/// Domain events for WebsiteSaleSetting — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WebsiteSaleSetting>)` variant.
pub type WebsiteSaleSettingEvent = CrudEvent<WebsiteSaleSetting>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WebsiteSaleSetting events.
pub type WebsiteSaleSettingEventPublisher = Arc<dyn CrudEventPublisher<WebsiteSaleSetting> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWebsiteSaleSettingEventPublisher = NoOpCrudEventPublisher<WebsiteSaleSetting>;
