//! Event handler trait for WebsiteSaleSetting events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WebsiteSaleSettingEvent;

/// Event handler for WebsiteSaleSetting events.
/// Implement this trait to react to WebsiteSaleSetting lifecycle events.
pub trait WebsiteSaleSettingEventHandler: EventHandler<WebsiteSaleSettingEvent> {}
