//! Domain events for WishlistItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WishlistItem;

/// Domain events for WishlistItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WishlistItem>)` variant.
pub type WishlistItemEvent = CrudEvent<WishlistItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WishlistItem events.
pub type WishlistItemEventPublisher = Arc<dyn CrudEventPublisher<WishlistItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWishlistItemEventPublisher = NoOpCrudEventPublisher<WishlistItem>;
