//! Event handler trait for WishlistItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WishlistItemEvent;

/// Event handler for WishlistItem events.
/// Implement this trait to react to WishlistItem lifecycle events.
pub trait WishlistItemEventHandler: EventHandler<WishlistItemEvent> {}
