//! CheckoutSession seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CheckoutSession data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CHECKOUTSESSION SEEDER
// ============================================================================

/// Seeder for checkout_session
pub struct SeedCheckoutSessionSeeder;

impl SeedCheckoutSessionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCheckoutSessionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCheckoutSessionSeeder {
    fn name(&self) -> &'static str {
        "SeedCheckoutSessionSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.checkout_sessions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.checkout_sessions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/checkout_session_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.checkout_sessions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
