//! Database seeders for the storefront module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod cart_seeder;
mod cart_line_seeder;
mod checkout_session_seeder;
mod product_listing_seeder;
mod product_price_seeder;
mod recovery_invite_seeder;
mod shopper_party_seeder;
mod storefront_audit_log_seeder;
mod website_sale_setting_seeder;

pub use cart_seeder::SeedCartSeeder;
pub use cart_line_seeder::SeedCartLineSeeder;
pub use checkout_session_seeder::SeedCheckoutSessionSeeder;
pub use product_listing_seeder::SeedProductListingSeeder;
pub use product_price_seeder::SeedProductPriceSeeder;
pub use recovery_invite_seeder::SeedRecoveryInviteSeeder;
pub use shopper_party_seeder::SeedShopperPartySeeder;
pub use storefront_audit_log_seeder::SeedStorefrontAuditLogSeeder;
pub use website_sale_setting_seeder::SeedWebsiteSaleSettingSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
