//! ProductListing seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ProductListing data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PRODUCTLISTING SEEDER
// ============================================================================

/// Seeder for product_listing
pub struct SeedProductListingSeeder;

impl SeedProductListingSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedProductListingSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedProductListingSeeder {
    fn name(&self) -> &'static str {
        "SeedProductListingSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.product_listings table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.product_listings")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/product_listing_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.product_listings")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
