//! ProductPrice seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ProductPrice data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PRODUCTPRICE SEEDER
// ============================================================================

/// Seeder for product_price
pub struct SeedProductPriceSeeder;

impl SeedProductPriceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedProductPriceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedProductPriceSeeder {
    fn name(&self) -> &'static str {
        "SeedProductPriceSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.product_prices table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.product_prices")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/product_price_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.product_prices")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
