//! RecoveryInvite seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial RecoveryInvite data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// RECOVERYINVITE SEEDER
// ============================================================================

/// Seeder for recovery_invite
pub struct SeedRecoveryInviteSeeder;

impl SeedRecoveryInviteSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRecoveryInviteSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRecoveryInviteSeeder {
    fn name(&self) -> &'static str {
        "SeedRecoveryInviteSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.recovery_invites table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.recovery_invites")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/recovery_invite_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.recovery_invites")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
