//! ShopperParty seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ShopperParty data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SHOPPERPARTY SEEDER
// ============================================================================

/// Seeder for shopper_party
pub struct SeedShopperPartySeeder;

impl SeedShopperPartySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedShopperPartySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedShopperPartySeeder {
    fn name(&self) -> &'static str {
        "SeedShopperPartySeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.shopper_parties table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.shopper_parties")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/shopper_party_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.shopper_parties")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
