//! StorefrontAuditLog seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial StorefrontAuditLog data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// STOREFRONTAUDITLOG SEEDER
// ============================================================================

/// Seeder for storefront_audit_log
pub struct SeedStorefrontAuditLogSeeder;

impl SeedStorefrontAuditLogSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedStorefrontAuditLogSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedStorefrontAuditLogSeeder {
    fn name(&self) -> &'static str {
        "SeedStorefrontAuditLogSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.storefront_audit_log table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.storefront_audit_log")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/storefront_audit_log_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.storefront_audit_log")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
