//! WebsiteSaleSetting seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial WebsiteSaleSetting data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// WEBSITESALESETTING SEEDER
// ============================================================================

/// Seeder for website_sale_setting
pub struct SeedWebsiteSaleSettingSeeder;

impl SeedWebsiteSaleSettingSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedWebsiteSaleSettingSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedWebsiteSaleSettingSeeder {
    fn name(&self) -> &'static str {
        "SeedWebsiteSaleSettingSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.website_sale_settings table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.website_sale_settings")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/website_sale_setting_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.website_sale_settings")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
