//! WishlistItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial WishlistItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// WISHLISTITEM SEEDER
// ============================================================================

/// Seeder for wishlist_item
pub struct SeedWishlistItemSeeder;

impl SeedWishlistItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedWishlistItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedWishlistItemSeeder {
    fn name(&self) -> &'static str {
        "SeedWishlistItemSeeder"
    }

    fn order(&self) -> i32 {
        10
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if storefront.wishlist_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM storefront.wishlist_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/wishlist_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM storefront.wishlist_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

