//! Repository trait for Cart aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Cart aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Cart, StorefrontCartState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CartPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CartPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CartPaginatedResult {
    pub data: Vec<Cart>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CartFilter {
    pub website_id: Option<Uuid>,
    pub visitor_id: Option<Uuid>,
    pub portal_user_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub state: Option<StorefrontCartState>,
    pub coupon_code: Option<String>,
    pub delivery_carrier_id: Option<Uuid>,
}

impl CartFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.visitor_id.is_some() || self.portal_user_id.is_some() || self.party_id.is_some() || self.state.is_some() || self.coupon_code.is_some() || self.delivery_carrier_id.is_some()
    }
}

/// Repository trait for Cart aggregate
///
/// This trait defines the persistence contract for Cart entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CartRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new cart entity
    async fn save(&self, entity: &Cart) -> Result<Cart>;

    /// Find cart by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Cart>>;

    /// Find all cart entities
    async fn find_all(&self) -> Result<Vec<Cart>>;

    /// Update cart by ID
    async fn update(&self, id: &str, entity: &Cart) -> Result<Option<Cart>>;

    /// Delete cart by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List cart with pagination
    async fn list(&self, params: CartPaginationParams) -> Result<CartPaginatedResult>;

    /// List cart with pagination and filters
    async fn list_with_filters(&self, params: CartPaginationParams, filters: CartFilter) -> Result<CartPaginatedResult>;

    /// Count all cart entities
    async fn count(&self) -> Result<u64>;

    /// Count cart entities matching filters
    async fn count_with_filters(&self, filters: CartFilter) -> Result<u64>;

    /// Check if cart exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete cart by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted cart by ID
    async fn restore(&self, id: &str) -> Result<Option<Cart>>;

    /// List soft-deleted cart entities
    async fn list_deleted(&self, params: CartPaginationParams) -> Result<CartPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save cart entities
    async fn bulk_save(&self, entities: &[Cart]) -> Result<Vec<Cart>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
