//! Repository trait for CartLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CartLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CartLine;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CartLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CartLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CartLinePaginatedResult {
    pub data: Vec<CartLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CartLineFilter {
    pub cart_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
}

impl CartLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.cart_id.is_some() || self.item_id.is_some()
    }
}

/// Repository trait for CartLine aggregate
///
/// This trait defines the persistence contract for CartLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CartLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new cart_line entity
    async fn save(&self, entity: &CartLine) -> Result<CartLine>;

    /// Find cart_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CartLine>>;

    /// Find all cart_line entities
    async fn find_all(&self) -> Result<Vec<CartLine>>;

    /// Update cart_line by ID
    async fn update(&self, id: &str, entity: &CartLine) -> Result<Option<CartLine>>;

    /// Delete cart_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List cart_line with pagination
    async fn list(&self, params: CartLinePaginationParams) -> Result<CartLinePaginatedResult>;

    /// List cart_line with pagination and filters
    async fn list_with_filters(&self, params: CartLinePaginationParams, filters: CartLineFilter) -> Result<CartLinePaginatedResult>;

    /// Count all cart_line entities
    async fn count(&self) -> Result<u64>;

    /// Count cart_line entities matching filters
    async fn count_with_filters(&self, filters: CartLineFilter) -> Result<u64>;

    /// Check if cart_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete cart_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted cart_line by ID
    async fn restore(&self, id: &str) -> Result<Option<CartLine>>;

    /// List soft-deleted cart_line entities
    async fn list_deleted(&self, params: CartLinePaginationParams) -> Result<CartLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save cart_line entities
    async fn bulk_save(&self, entities: &[CartLine]) -> Result<Vec<CartLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
