//! Repository trait for CheckoutSession aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CheckoutSession aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{CheckoutSession, StorefrontCheckoutState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CheckoutSessionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CheckoutSessionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CheckoutSessionPaginatedResult {
    pub data: Vec<CheckoutSession>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CheckoutSessionFilter {
    pub cart_id: Option<Uuid>,
    pub website_id: Option<Uuid>,
    pub sales_order_id: Option<Uuid>,
    pub gateway_transaction_id: Option<Uuid>,
    pub provider_code: Option<String>,
    pub provider_reference: Option<String>,
    pub state: Option<StorefrontCheckoutState>,
}

impl CheckoutSessionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.cart_id.is_some() || self.website_id.is_some() || self.sales_order_id.is_some() || self.gateway_transaction_id.is_some() || self.provider_code.is_some() || self.provider_reference.is_some() || self.state.is_some()
    }
}

/// Repository trait for CheckoutSession aggregate
///
/// This trait defines the persistence contract for CheckoutSession entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CheckoutSessionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new checkout_session entity
    async fn save(&self, entity: &CheckoutSession) -> Result<CheckoutSession>;

    /// Find checkout_session by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CheckoutSession>>;

    /// Find all checkout_session entities
    async fn find_all(&self) -> Result<Vec<CheckoutSession>>;

    /// Update checkout_session by ID
    async fn update(&self, id: &str, entity: &CheckoutSession) -> Result<Option<CheckoutSession>>;

    /// Delete checkout_session by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List checkout_session with pagination
    async fn list(&self, params: CheckoutSessionPaginationParams) -> Result<CheckoutSessionPaginatedResult>;

    /// List checkout_session with pagination and filters
    async fn list_with_filters(&self, params: CheckoutSessionPaginationParams, filters: CheckoutSessionFilter) -> Result<CheckoutSessionPaginatedResult>;

    /// Count all checkout_session entities
    async fn count(&self) -> Result<u64>;

    /// Count checkout_session entities matching filters
    async fn count_with_filters(&self, filters: CheckoutSessionFilter) -> Result<u64>;

    /// Check if checkout_session exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete checkout_session by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted checkout_session by ID
    async fn restore(&self, id: &str) -> Result<Option<CheckoutSession>>;

    /// List soft-deleted checkout_session entities
    async fn list_deleted(&self, params: CheckoutSessionPaginationParams) -> Result<CheckoutSessionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save checkout_session entities
    async fn bulk_save(&self, entities: &[CheckoutSession]) -> Result<Vec<CheckoutSession>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
