//! Repository trait for PickupLocation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PickupLocation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PickupLocation;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PickupLocationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PickupLocationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PickupLocationPaginatedResult {
    pub data: Vec<PickupLocation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PickupLocationFilter {
    pub website_id: Option<Uuid>,
    pub warehouse_id: Option<Uuid>,
    pub name: Option<String>,
    pub address_line1: Option<String>,
    pub city: Option<String>,
    pub postal_code: Option<String>,
    pub country: Option<String>,
    pub is_active: Option<bool>,
}

impl PickupLocationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.warehouse_id.is_some() || self.name.is_some() || self.address_line1.is_some() || self.city.is_some() || self.postal_code.is_some() || self.country.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for PickupLocation aggregate
///
/// This trait defines the persistence contract for PickupLocation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PickupLocationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pickup_location entity
    async fn save(&self, entity: &PickupLocation) -> Result<PickupLocation>;

    /// Find pickup_location by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PickupLocation>>;

    /// Find all pickup_location entities
    async fn find_all(&self) -> Result<Vec<PickupLocation>>;

    /// Update pickup_location by ID
    async fn update(&self, id: &str, entity: &PickupLocation) -> Result<Option<PickupLocation>>;

    /// Delete pickup_location by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pickup_location with pagination
    async fn list(&self, params: PickupLocationPaginationParams) -> Result<PickupLocationPaginatedResult>;

    /// List pickup_location with pagination and filters
    async fn list_with_filters(&self, params: PickupLocationPaginationParams, filters: PickupLocationFilter) -> Result<PickupLocationPaginatedResult>;

    /// Count all pickup_location entities
    async fn count(&self) -> Result<u64>;

    /// Count pickup_location entities matching filters
    async fn count_with_filters(&self, filters: PickupLocationFilter) -> Result<u64>;

    /// Check if pickup_location exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pickup_location by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pickup_location by ID
    async fn restore(&self, id: &str) -> Result<Option<PickupLocation>>;

    /// List soft-deleted pickup_location entities
    async fn list_deleted(&self, params: PickupLocationPaginationParams) -> Result<PickupLocationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pickup_location entities
    async fn bulk_save(&self, entities: &[PickupLocation]) -> Result<Vec<PickupLocation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
