//! Repository trait for ProductPrice aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ProductPrice aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ProductPrice;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProductPricePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ProductPricePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ProductPricePaginatedResult {
    pub data: Vec<ProductPrice>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProductPriceFilter {
    pub website_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub currency: Option<String>,
}

impl ProductPriceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.item_id.is_some() || self.currency.is_some()
    }
}

/// Repository trait for ProductPrice aggregate
///
/// This trait defines the persistence contract for ProductPrice entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ProductPriceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new product_price entity
    async fn save(&self, entity: &ProductPrice) -> Result<ProductPrice>;

    /// Find product_price by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ProductPrice>>;

    /// Find all product_price entities
    async fn find_all(&self) -> Result<Vec<ProductPrice>>;

    /// Update product_price by ID
    async fn update(&self, id: &str, entity: &ProductPrice) -> Result<Option<ProductPrice>>;

    /// Delete product_price by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List product_price with pagination
    async fn list(&self, params: ProductPricePaginationParams) -> Result<ProductPricePaginatedResult>;

    /// List product_price with pagination and filters
    async fn list_with_filters(&self, params: ProductPricePaginationParams, filters: ProductPriceFilter) -> Result<ProductPricePaginatedResult>;

    /// Count all product_price entities
    async fn count(&self) -> Result<u64>;

    /// Count product_price entities matching filters
    async fn count_with_filters(&self, filters: ProductPriceFilter) -> Result<u64>;

    /// Check if product_price exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete product_price by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted product_price by ID
    async fn restore(&self, id: &str) -> Result<Option<ProductPrice>>;

    /// List soft-deleted product_price entities
    async fn list_deleted(&self, params: ProductPricePaginationParams) -> Result<ProductPricePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save product_price entities
    async fn bulk_save(&self, entities: &[ProductPrice]) -> Result<Vec<ProductPrice>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
