//! Repository trait for ProductListing aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ProductListing aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ProductListing;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProductListingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ProductListingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ProductListingPaginatedResult {
    pub data: Vec<ProductListing>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProductListingFilter {
    pub website_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub sale_ok: Option<bool>,
    pub is_published: Option<bool>,
}

impl ProductListingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.item_id.is_some() || self.sale_ok.is_some() || self.is_published.is_some()
    }
}

/// Repository trait for ProductListing aggregate
///
/// This trait defines the persistence contract for ProductListing entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ProductListingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new product_listing entity
    async fn save(&self, entity: &ProductListing) -> Result<ProductListing>;

    /// Find product_listing by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ProductListing>>;

    /// Find all product_listing entities
    async fn find_all(&self) -> Result<Vec<ProductListing>>;

    /// Update product_listing by ID
    async fn update(&self, id: &str, entity: &ProductListing) -> Result<Option<ProductListing>>;

    /// Delete product_listing by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List product_listing with pagination
    async fn list(&self, params: ProductListingPaginationParams) -> Result<ProductListingPaginatedResult>;

    /// List product_listing with pagination and filters
    async fn list_with_filters(&self, params: ProductListingPaginationParams, filters: ProductListingFilter) -> Result<ProductListingPaginatedResult>;

    /// Count all product_listing entities
    async fn count(&self) -> Result<u64>;

    /// Count product_listing entities matching filters
    async fn count_with_filters(&self, filters: ProductListingFilter) -> Result<u64>;

    /// Check if product_listing exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete product_listing by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted product_listing by ID
    async fn restore(&self, id: &str) -> Result<Option<ProductListing>>;

    /// List soft-deleted product_listing entities
    async fn list_deleted(&self, params: ProductListingPaginationParams) -> Result<ProductListingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save product_listing entities
    async fn bulk_save(&self, entities: &[ProductListing]) -> Result<Vec<ProductListing>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
