//! Repository trait for RecoveryInvite aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RecoveryInvite aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RecoveryInvite;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RecoveryInvitePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RecoveryInvitePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RecoveryInvitePaginatedResult {
    pub data: Vec<RecoveryInvite>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RecoveryInviteFilter {
    pub cart_id: Option<Uuid>,
    pub template_ref: Option<String>,
    pub delivery_state: Option<String>,
}

impl RecoveryInviteFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.cart_id.is_some() || self.template_ref.is_some() || self.delivery_state.is_some()
    }
}

/// Repository trait for RecoveryInvite aggregate
///
/// This trait defines the persistence contract for RecoveryInvite entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RecoveryInviteRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new recovery_invite entity
    async fn save(&self, entity: &RecoveryInvite) -> Result<RecoveryInvite>;

    /// Find recovery_invite by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RecoveryInvite>>;

    /// Find all recovery_invite entities
    async fn find_all(&self) -> Result<Vec<RecoveryInvite>>;

    /// Update recovery_invite by ID
    async fn update(&self, id: &str, entity: &RecoveryInvite) -> Result<Option<RecoveryInvite>>;

    /// Delete recovery_invite by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List recovery_invite with pagination
    async fn list(&self, params: RecoveryInvitePaginationParams) -> Result<RecoveryInvitePaginatedResult>;

    /// List recovery_invite with pagination and filters
    async fn list_with_filters(&self, params: RecoveryInvitePaginationParams, filters: RecoveryInviteFilter) -> Result<RecoveryInvitePaginatedResult>;

    /// Count all recovery_invite entities
    async fn count(&self) -> Result<u64>;

    /// Count recovery_invite entities matching filters
    async fn count_with_filters(&self, filters: RecoveryInviteFilter) -> Result<u64>;

    /// Check if recovery_invite exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete recovery_invite by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted recovery_invite by ID
    async fn restore(&self, id: &str) -> Result<Option<RecoveryInvite>>;

    /// List soft-deleted recovery_invite entities
    async fn list_deleted(&self, params: RecoveryInvitePaginationParams) -> Result<RecoveryInvitePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save recovery_invite entities
    async fn bulk_save(&self, entities: &[RecoveryInvite]) -> Result<Vec<RecoveryInvite>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
