//! Repository trait for ShopperParty aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ShopperParty aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ShopperParty;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShopperPartyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ShopperPartyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ShopperPartyPaginatedResult {
    pub data: Vec<ShopperParty>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShopperPartyFilter {
    pub company_id: Option<Uuid>,
    pub email_normalized: Option<String>,
    pub party_id: Option<Uuid>,
}

impl ShopperPartyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.email_normalized.is_some() || self.party_id.is_some()
    }
}

/// Repository trait for ShopperParty aggregate
///
/// This trait defines the persistence contract for ShopperParty entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ShopperPartyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new shopper_party entity
    async fn save(&self, entity: &ShopperParty) -> Result<ShopperParty>;

    /// Find shopper_party by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ShopperParty>>;

    /// Find all shopper_party entities
    async fn find_all(&self) -> Result<Vec<ShopperParty>>;

    /// Update shopper_party by ID
    async fn update(&self, id: &str, entity: &ShopperParty) -> Result<Option<ShopperParty>>;

    /// Delete shopper_party by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List shopper_party with pagination
    async fn list(&self, params: ShopperPartyPaginationParams) -> Result<ShopperPartyPaginatedResult>;

    /// List shopper_party with pagination and filters
    async fn list_with_filters(&self, params: ShopperPartyPaginationParams, filters: ShopperPartyFilter) -> Result<ShopperPartyPaginatedResult>;

    /// Count all shopper_party entities
    async fn count(&self) -> Result<u64>;

    /// Count shopper_party entities matching filters
    async fn count_with_filters(&self, filters: ShopperPartyFilter) -> Result<u64>;

    /// Check if shopper_party exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete shopper_party by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted shopper_party by ID
    async fn restore(&self, id: &str) -> Result<Option<ShopperParty>>;

    /// List soft-deleted shopper_party entities
    async fn list_deleted(&self, params: ShopperPartyPaginationParams) -> Result<ShopperPartyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save shopper_party entities
    async fn bulk_save(&self, entities: &[ShopperParty]) -> Result<Vec<ShopperParty>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
