//! Repository trait for StorefrontAuditLog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the StorefrontAuditLog aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{StorefrontAuditLog, StorefrontAuditEvent};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StorefrontAuditLogPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl StorefrontAuditLogPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct StorefrontAuditLogPaginatedResult {
    pub data: Vec<StorefrontAuditLog>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StorefrontAuditLogFilter {
    pub website_id: Option<Uuid>,
    pub event: Option<StorefrontAuditEvent>,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
}

impl StorefrontAuditLogFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.event.is_some() || self.actor.is_some() || self.subject_type.is_some() || self.subject_id.is_some()
    }
}

/// Repository trait for StorefrontAuditLog aggregate
///
/// This trait defines the persistence contract for StorefrontAuditLog entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait StorefrontAuditLogRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new storefront_audit_log entity
    async fn save(&self, entity: &StorefrontAuditLog) -> Result<StorefrontAuditLog>;

    /// Find storefront_audit_log by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<StorefrontAuditLog>>;

    /// Find all storefront_audit_log entities
    async fn find_all(&self) -> Result<Vec<StorefrontAuditLog>>;

    /// Update storefront_audit_log by ID
    async fn update(&self, id: &str, entity: &StorefrontAuditLog) -> Result<Option<StorefrontAuditLog>>;

    /// Delete storefront_audit_log by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List storefront_audit_log with pagination
    async fn list(&self, params: StorefrontAuditLogPaginationParams) -> Result<StorefrontAuditLogPaginatedResult>;

    /// List storefront_audit_log with pagination and filters
    async fn list_with_filters(&self, params: StorefrontAuditLogPaginationParams, filters: StorefrontAuditLogFilter) -> Result<StorefrontAuditLogPaginatedResult>;

    /// Count all storefront_audit_log entities
    async fn count(&self) -> Result<u64>;

    /// Count storefront_audit_log entities matching filters
    async fn count_with_filters(&self, filters: StorefrontAuditLogFilter) -> Result<u64>;

    /// Check if storefront_audit_log exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save storefront_audit_log entities
    async fn bulk_save(&self, entities: &[StorefrontAuditLog]) -> Result<Vec<StorefrontAuditLog>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
