//! Repository trait for WebsiteSaleSetting aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WebsiteSaleSetting aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{WebsiteSaleSetting, StorefrontAccessGate};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteSaleSettingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WebsiteSaleSettingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WebsiteSaleSettingPaginatedResult {
    pub data: Vec<WebsiteSaleSetting>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WebsiteSaleSettingFilter {
    pub website_id: Option<Uuid>,
    pub access_gate: Option<StorefrontAccessGate>,
    pub default_customer_group_id: Option<Uuid>,
    pub guest_party_id: Option<Uuid>,
    pub recovery_template_ref: Option<String>,
}

impl WebsiteSaleSettingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.access_gate.is_some() || self.default_customer_group_id.is_some() || self.guest_party_id.is_some() || self.recovery_template_ref.is_some()
    }
}

/// Repository trait for WebsiteSaleSetting aggregate
///
/// This trait defines the persistence contract for WebsiteSaleSetting entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WebsiteSaleSettingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new website_sale_setting entity
    async fn save(&self, entity: &WebsiteSaleSetting) -> Result<WebsiteSaleSetting>;

    /// Find website_sale_setting by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WebsiteSaleSetting>>;

    /// Find all website_sale_setting entities
    async fn find_all(&self) -> Result<Vec<WebsiteSaleSetting>>;

    /// Update website_sale_setting by ID
    async fn update(&self, id: &str, entity: &WebsiteSaleSetting) -> Result<Option<WebsiteSaleSetting>>;

    /// Delete website_sale_setting by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List website_sale_setting with pagination
    async fn list(&self, params: WebsiteSaleSettingPaginationParams) -> Result<WebsiteSaleSettingPaginatedResult>;

    /// List website_sale_setting with pagination and filters
    async fn list_with_filters(&self, params: WebsiteSaleSettingPaginationParams, filters: WebsiteSaleSettingFilter) -> Result<WebsiteSaleSettingPaginatedResult>;

    /// Count all website_sale_setting entities
    async fn count(&self) -> Result<u64>;

    /// Count website_sale_setting entities matching filters
    async fn count_with_filters(&self, filters: WebsiteSaleSettingFilter) -> Result<u64>;

    /// Check if website_sale_setting exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete website_sale_setting by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted website_sale_setting by ID
    async fn restore(&self, id: &str) -> Result<Option<WebsiteSaleSetting>>;

    /// List soft-deleted website_sale_setting entities
    async fn list_deleted(&self, params: WebsiteSaleSettingPaginationParams) -> Result<WebsiteSaleSettingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save website_sale_setting entities
    async fn bulk_save(&self, entities: &[WebsiteSaleSetting]) -> Result<Vec<WebsiteSaleSetting>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
