//! Repository trait for WishlistItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WishlistItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::WishlistItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WishlistItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WishlistItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WishlistItemPaginatedResult {
    pub data: Vec<WishlistItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WishlistItemFilter {
    pub website_id: Option<Uuid>,
    pub visitor_id: Option<Uuid>,
    pub portal_user_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub notify_on_stock: Option<bool>,
    pub contact_email: Option<String>,
}

impl WishlistItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.website_id.is_some() || self.visitor_id.is_some() || self.portal_user_id.is_some() || self.item_id.is_some() || self.notify_on_stock.is_some() || self.contact_email.is_some()
    }
}

/// Repository trait for WishlistItem aggregate
///
/// This trait defines the persistence contract for WishlistItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WishlistItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new wishlist_item entity
    async fn save(&self, entity: &WishlistItem) -> Result<WishlistItem>;

    /// Find wishlist_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WishlistItem>>;

    /// Find all wishlist_item entities
    async fn find_all(&self) -> Result<Vec<WishlistItem>>;

    /// Update wishlist_item by ID
    async fn update(&self, id: &str, entity: &WishlistItem) -> Result<Option<WishlistItem>>;

    /// Delete wishlist_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List wishlist_item with pagination
    async fn list(&self, params: WishlistItemPaginationParams) -> Result<WishlistItemPaginatedResult>;

    /// List wishlist_item with pagination and filters
    async fn list_with_filters(&self, params: WishlistItemPaginationParams, filters: WishlistItemFilter) -> Result<WishlistItemPaginatedResult>;

    /// Count all wishlist_item entities
    async fn count(&self) -> Result<u64>;

    /// Count wishlist_item entities matching filters
    async fn count_with_filters(&self, filters: WishlistItemFilter) -> Result<u64>;

    /// Check if wishlist_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete wishlist_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted wishlist_item by ID
    async fn restore(&self, id: &str) -> Result<Option<WishlistItem>>;

    /// List soft-deleted wishlist_item entities
    async fn list_deleted(&self, params: WishlistItemPaginationParams) -> Result<WishlistItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save wishlist_item entities
    async fn bulk_save(&self, entities: &[WishlistItem]) -> Result<Vec<WishlistItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
