//! Repository for CartLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CartLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CartLine;

/// Table name for CartLine entities
pub const TABLE_NAME: &str = "storefront.cart_lines";

/// Repository for CartLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CartLineRepository(
    backbone_orm::GenericCrudRepository<CartLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CartLineRepository {
    type Target = backbone_orm::GenericCrudRepository<CartLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CartLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CartLineRepository, CartLine, soft_delete);
