//! Repository for CheckoutSession entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CheckoutSession, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CheckoutSession;

/// Table name for CheckoutSession entities
pub const TABLE_NAME: &str = "storefront.checkout_sessions";

/// Repository for CheckoutSession entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CheckoutSessionRepository(
    backbone_orm::GenericCrudRepository<CheckoutSession, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CheckoutSessionRepository {
    type Target = backbone_orm::GenericCrudRepository<CheckoutSession, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CheckoutSessionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CheckoutSessionRepository, CheckoutSession, soft_delete);
