//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod cart_repository;
mod cart_line_repository;
mod checkout_session_repository;
mod pickup_location_repository;
mod product_listing_repository;
mod product_price_repository;
mod recovery_invite_repository;
mod shopper_party_repository;
mod website_sale_setting_repository;
mod wishlist_item_repository;

// Custom persistence modules
// <<< CUSTOM
/// Bind the ambient organization scope onto a connection this module opened
/// itself. Every write transaction the module owns calls this right after
/// `begin`, so the org fence (once the composition declares this schema
/// scoped) sees the caller's entitlements instead of refusing the write at
/// the kind guard. A no-op while no ambient scope exists (seeder and
/// host-consumer paths), which keeps the module correct before the fence
/// lands.
pub(crate) async fn relay_ambient_scope(
    conn: &mut sqlx::PgConnection,
) -> Result<(), sqlx::Error> {
    if let Some(scope) = backbone_orm::org_scope::current_org_scope() {
        backbone_orm::org_scope::bind_org_scope_on(conn, &scope).await?;
    }
    Ok(())
}
// END CUSTOM

// Re-exports
pub use cart_repository::CartRepository;
pub use cart_line_repository::CartLineRepository;
pub use checkout_session_repository::CheckoutSessionRepository;
pub use pickup_location_repository::PickupLocationRepository;
pub use product_listing_repository::ProductListingRepository;
pub use product_price_repository::ProductPriceRepository;
pub use recovery_invite_repository::RecoveryInviteRepository;
pub use shopper_party_repository::ShopperPartyRepository;
pub use website_sale_setting_repository::WebsiteSaleSettingRepository;
pub use wishlist_item_repository::WishlistItemRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
