//! Repository for PickupLocation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PickupLocation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PickupLocation;

/// Table name for PickupLocation entities
pub const TABLE_NAME: &str = "storefront.pickup_locations";

/// Repository for PickupLocation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PickupLocationRepository(
    backbone_orm::GenericCrudRepository<PickupLocation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PickupLocationRepository {
    type Target = backbone_orm::GenericCrudRepository<PickupLocation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PickupLocationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PickupLocationRepository, PickupLocation, soft_delete);
