//! Repository for ProductListing entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ProductListing, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ProductListing;

/// Table name for ProductListing entities
pub const TABLE_NAME: &str = "storefront.product_listings";

/// Repository for ProductListing entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProductListingRepository(
    backbone_orm::GenericCrudRepository<ProductListing, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProductListingRepository {
    type Target = backbone_orm::GenericCrudRepository<ProductListing, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProductListingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ProductListingRepository, ProductListing, soft_delete);
