//! Repository for ProductPrice entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ProductPrice, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ProductPrice;

/// Table name for ProductPrice entities
pub const TABLE_NAME: &str = "storefront.product_prices";

/// Repository for ProductPrice entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProductPriceRepository(
    backbone_orm::GenericCrudRepository<ProductPrice, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProductPriceRepository {
    type Target = backbone_orm::GenericCrudRepository<ProductPrice, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProductPriceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ProductPriceRepository, ProductPrice, soft_delete);
