//! Repository for ShopperParty entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ShopperParty, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ShopperParty;

/// Table name for ShopperParty entities
pub const TABLE_NAME: &str = "storefront.shopper_parties";

/// Repository for ShopperParty entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ShopperPartyRepository(
    backbone_orm::GenericCrudRepository<ShopperParty, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ShopperPartyRepository {
    type Target = backbone_orm::GenericCrudRepository<ShopperParty, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ShopperPartyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ShopperPartyRepository, ShopperParty, soft_delete);
