//! Repository for StorefrontAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<StorefrontAuditLog, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::StorefrontAuditLog;

/// Table name for StorefrontAuditLog entities
pub const TABLE_NAME: &str = "storefront.storefront_audit_log";

/// Repository for StorefrontAuditLog entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct StorefrontAuditLogRepository(
    backbone_orm::GenericCrudRepository<StorefrontAuditLog, backbone_orm::HardDelete>,
);

impl std::ops::Deref for StorefrontAuditLogRepository {
    type Target = backbone_orm::GenericCrudRepository<StorefrontAuditLog, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl StorefrontAuditLogRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(StorefrontAuditLogRepository, StorefrontAuditLog, no_soft_delete);
