//! Repository for WebsiteSaleSetting entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WebsiteSaleSetting, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WebsiteSaleSetting;

/// Table name for WebsiteSaleSetting entities
pub const TABLE_NAME: &str = "storefront.website_sale_settings";

/// Repository for WebsiteSaleSetting entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WebsiteSaleSettingRepository(
    backbone_orm::GenericCrudRepository<WebsiteSaleSetting, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WebsiteSaleSettingRepository {
    type Target = backbone_orm::GenericCrudRepository<WebsiteSaleSetting, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WebsiteSaleSettingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WebsiteSaleSettingRepository, WebsiteSaleSetting, soft_delete);
