//! Repository for WishlistItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WishlistItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WishlistItem;

/// Table name for WishlistItem entities
pub const TABLE_NAME: &str = "storefront.wishlist_items";

/// Repository for WishlistItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WishlistItemRepository(
    backbone_orm::GenericCrudRepository<WishlistItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WishlistItemRepository {
    type Target = backbone_orm::GenericCrudRepository<WishlistItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WishlistItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WishlistItemRepository, WishlistItem, soft_delete);
