//! Validator for CartLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CartLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CartLine;

/// Validator type alias for CartLine entities.
pub type CartLineValidator = EntityValidator<CartLine>;

/// Build a validator for CartLine with all schema-defined field rules.
pub fn cart_line_validator() -> CartLineValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
