//! Validator for Cart entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Cart>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::Cart;

/// Validator type alias for Cart entities.
pub type CartValidator = EntityValidator<Cart>;

/// Build a validator for Cart with all schema-defined field rules.
pub fn cart_validator() -> CartValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("coupon_code", |e: &Cart| e.coupon_code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
