//! Validator for CheckoutSession entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CheckoutSession>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::CheckoutSession;

/// Validator type alias for CheckoutSession entities.
pub type CheckoutSessionValidator = EntityValidator<CheckoutSession>;

/// Build a validator for CheckoutSession with all schema-defined field rules.
pub fn checkout_session_validator() -> CheckoutSessionValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("provider_code", |e: &CheckoutSession| e.provider_code.as_deref()))
        .rule(OptionalNotBlank::new("provider_reference", |e: &CheckoutSession| e.provider_reference.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
