//! Validator for PickupLocation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PickupLocation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PickupLocation;

/// Validator type alias for PickupLocation entities.
pub type PickupLocationValidator = EntityValidator<PickupLocation>;

/// Build a validator for PickupLocation with all schema-defined field rules.
pub fn pickup_location_validator() -> PickupLocationValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &PickupLocation| &e.name))
        .rule(OptionalNotBlank::new("address_line1", |e: &PickupLocation| e.address_line1.as_deref()))
        .rule(OptionalNotBlank::new("city", |e: &PickupLocation| e.city.as_deref()))
        .rule(OptionalNotBlank::new("postal_code", |e: &PickupLocation| e.postal_code.as_deref()))
        .rule(RequiredString::new("country", |e: &PickupLocation| &e.country))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
