//! Validator for ProductPrice entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ProductPrice>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::ProductPrice;

/// Validator type alias for ProductPrice entities.
pub type ProductPriceValidator = EntityValidator<ProductPrice>;

/// Build a validator for ProductPrice with all schema-defined field rules.
pub fn product_price_validator() -> ProductPriceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("currency", |e: &ProductPrice| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
