//! Validator for ProductListing entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ProductListing>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::ProductListing;

/// Validator type alias for ProductListing entities.
pub type ProductListingValidator = EntityValidator<ProductListing>;

/// Build a validator for ProductListing with all schema-defined field rules.
pub fn product_listing_validator() -> ProductListingValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
