//! Validator for RecoveryInvite entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RecoveryInvite>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::RecoveryInvite;

/// Validator type alias for RecoveryInvite entities.
pub type RecoveryInviteValidator = EntityValidator<RecoveryInvite>;

/// Build a validator for RecoveryInvite with all schema-defined field rules.
pub fn recovery_invite_validator() -> RecoveryInviteValidator {
    EntityValidator::new()
        .rule(RequiredString::new("template_ref", |e: &RecoveryInvite| &e.template_ref))
        .rule(RequiredString::new("delivery_state", |e: &RecoveryInvite| &e.delivery_state))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
