//! Validator for ShopperParty entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ShopperParty>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::ShopperParty;

/// Validator type alias for ShopperParty entities.
pub type ShopperPartyValidator = EntityValidator<ShopperParty>;

/// Build a validator for ShopperParty with all schema-defined field rules.
pub fn shopper_party_validator() -> ShopperPartyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("email_normalized", |e: &ShopperParty| &e.email_normalized))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
