//! Validator for StorefrontAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<StorefrontAuditLog>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::StorefrontAuditLog;

/// Validator type alias for StorefrontAuditLog entities.
pub type StorefrontAuditLogValidator = EntityValidator<StorefrontAuditLog>;

/// Build a validator for StorefrontAuditLog with all schema-defined field rules.
pub fn storefront_audit_log_validator() -> StorefrontAuditLogValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("subject_type", |e: &StorefrontAuditLog| e.subject_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
