//! Validator for WebsiteSaleSetting entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WebsiteSaleSetting>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::WebsiteSaleSetting;

/// Validator type alias for WebsiteSaleSetting entities.
pub type WebsiteSaleSettingValidator = EntityValidator<WebsiteSaleSetting>;

/// Build a validator for WebsiteSaleSetting with all schema-defined field rules.
pub fn website_sale_setting_validator() -> WebsiteSaleSettingValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("recovery_template_ref", |e: &WebsiteSaleSetting| e.recovery_template_ref.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
