//! Validator for WishlistItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WishlistItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::WishlistItem;

/// Validator type alias for WishlistItem entities.
pub type WishlistItemValidator = EntityValidator<WishlistItem>;

/// Build a validator for WishlistItem with all schema-defined field rules.
pub fn wishlist_item_validator() -> WishlistItemValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("contact_email", |e: &WishlistItem| e.contact_email.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
