//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod cart;
pub mod cart_line;
pub mod checkout_session;
pub mod product_listing;
pub mod product_price;
pub mod recovery_invite;
pub mod shopper_party;
pub mod storefront_audit_log;
pub mod website_sale_setting;
pub mod storefront_audit_event;
pub mod storefront_cart_state;
pub mod storefront_checkout_state;
pub mod storefront_access_gate;

// Re-exports
pub use cart::Cart;
pub use cart::CartBuilder;
pub use cart::CartId;
pub use cart_line::CartLine;
pub use cart_line::CartLineBuilder;
pub use cart_line::CartLineId;
pub use checkout_session::CheckoutSession;
pub use checkout_session::CheckoutSessionBuilder;
pub use checkout_session::CheckoutSessionId;
pub use product_listing::ProductListing;
pub use product_listing::ProductListingBuilder;
pub use product_listing::ProductListingId;
pub use product_price::ProductPrice;
pub use product_price::ProductPriceBuilder;
pub use product_price::ProductPriceId;
pub use recovery_invite::RecoveryInvite;
pub use recovery_invite::RecoveryInviteBuilder;
pub use recovery_invite::RecoveryInviteId;
pub use shopper_party::ShopperParty;
pub use shopper_party::ShopperPartyBuilder;
pub use shopper_party::ShopperPartyId;
pub use storefront_audit_log::StorefrontAuditLog;
pub use storefront_audit_log::StorefrontAuditLogBuilder;
pub use storefront_audit_log::StorefrontAuditLogId;
pub use website_sale_setting::WebsiteSaleSetting;
pub use website_sale_setting::WebsiteSaleSettingBuilder;
pub use website_sale_setting::WebsiteSaleSettingId;
pub use storefront_audit_event::StorefrontAuditEvent;
pub use storefront_cart_state::StorefrontCartState;
pub use storefront_checkout_state::StorefrontCheckoutState;
pub use storefront_access_gate::StorefrontAccessGate;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
