//! Storefront Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CartService;
use crate::application::service::CartLineService;
use crate::application::service::CheckoutSessionService;
use crate::application::service::ProductListingService;
use crate::application::service::ProductPriceService;
use crate::application::service::RecoveryInviteService;
use crate::application::service::ShopperPartyService;
use crate::application::service::StorefrontAuditLogService;
use crate::application::service::WebsiteSaleSettingService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Cart service
    pub cart_service: Arc<CartService>,
    /// CartLine service
    pub cart_line_service: Arc<CartLineService>,
    /// CheckoutSession service
    pub checkout_session_service: Arc<CheckoutSessionService>,
    /// ProductListing service
    pub product_listing_service: Arc<ProductListingService>,
    /// ProductPrice service
    pub product_price_service: Arc<ProductPriceService>,
    /// RecoveryInvite service
    pub recovery_invite_service: Arc<RecoveryInviteService>,
    /// ShopperParty service
    pub shopper_party_service: Arc<ShopperPartyService>,
    /// StorefrontAuditLog service
    pub storefront_audit_log_service: Arc<StorefrontAuditLogService>,
    /// WebsiteSaleSetting service
    pub website_sale_setting_service: Arc<WebsiteSaleSettingService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        cart_service: Arc<CartService>,
        cart_line_service: Arc<CartLineService>,
        checkout_session_service: Arc<CheckoutSessionService>,
        product_listing_service: Arc<ProductListingService>,
        product_price_service: Arc<ProductPriceService>,
        recovery_invite_service: Arc<RecoveryInviteService>,
        shopper_party_service: Arc<ShopperPartyService>,
        storefront_audit_log_service: Arc<StorefrontAuditLogService>,
        website_sale_setting_service: Arc<WebsiteSaleSettingService>
    ) -> Self {
        Self {
            cart_service,
            cart_line_service,
            checkout_session_service,
            product_listing_service,
            product_price_service,
            recovery_invite_service,
            shopper_party_service,
            storefront_audit_log_service,
            website_sale_setting_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::StorefrontModule) -> Self {
        Self {
            cart_service: module.cart_service.clone(),
            cart_line_service: module.cart_line_service.clone(),
            checkout_session_service: module.checkout_session_service.clone(),
            product_listing_service: module.product_listing_service.clone(),
            product_price_service: module.product_price_service.clone(),
            recovery_invite_service: module.recovery_invite_service.clone(),
            shopper_party_service: module.shopper_party_service.clone(),
            storefront_audit_log_service: module.storefront_audit_log_service.clone(),
            website_sale_setting_service: module.website_sale_setting_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    cart_service: Option<Arc<CartService>>,
    cart_line_service: Option<Arc<CartLineService>>,
    checkout_session_service: Option<Arc<CheckoutSessionService>>,
    product_listing_service: Option<Arc<ProductListingService>>,
    product_price_service: Option<Arc<ProductPriceService>>,
    recovery_invite_service: Option<Arc<RecoveryInviteService>>,
    shopper_party_service: Option<Arc<ShopperPartyService>>,
    storefront_audit_log_service: Option<Arc<StorefrontAuditLogService>>,
    website_sale_setting_service: Option<Arc<WebsiteSaleSettingService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Cart service.
    pub fn with_cart_service(mut self, service: Arc<CartService>) -> Self {
        self.cart_service = Some(service);
        self
    }

    /// Set the CartLine service.
    pub fn with_cart_line_service(mut self, service: Arc<CartLineService>) -> Self {
        self.cart_line_service = Some(service);
        self
    }

    /// Set the CheckoutSession service.
    pub fn with_checkout_session_service(mut self, service: Arc<CheckoutSessionService>) -> Self {
        self.checkout_session_service = Some(service);
        self
    }

    /// Set the ProductListing service.
    pub fn with_product_listing_service(mut self, service: Arc<ProductListingService>) -> Self {
        self.product_listing_service = Some(service);
        self
    }

    /// Set the ProductPrice service.
    pub fn with_product_price_service(mut self, service: Arc<ProductPriceService>) -> Self {
        self.product_price_service = Some(service);
        self
    }

    /// Set the RecoveryInvite service.
    pub fn with_recovery_invite_service(mut self, service: Arc<RecoveryInviteService>) -> Self {
        self.recovery_invite_service = Some(service);
        self
    }

    /// Set the ShopperParty service.
    pub fn with_shopper_party_service(mut self, service: Arc<ShopperPartyService>) -> Self {
        self.shopper_party_service = Some(service);
        self
    }

    /// Set the StorefrontAuditLog service.
    pub fn with_storefront_audit_log_service(mut self, service: Arc<StorefrontAuditLogService>) -> Self {
        self.storefront_audit_log_service = Some(service);
        self
    }

    /// Set the WebsiteSaleSetting service.
    pub fn with_website_sale_setting_service(mut self, service: Arc<WebsiteSaleSettingService>) -> Self {
        self.website_sale_setting_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            cart_service: self.cart_service.expect("cart_service is required"),
            cart_line_service: self.cart_line_service.expect("cart_line_service is required"),
            checkout_session_service: self.checkout_session_service.expect("checkout_session_service is required"),
            product_listing_service: self.product_listing_service.expect("product_listing_service is required"),
            product_price_service: self.product_price_service.expect("product_price_service is required"),
            recovery_invite_service: self.recovery_invite_service.expect("recovery_invite_service is required"),
            shopper_party_service: self.shopper_party_service.expect("shopper_party_service is required"),
            storefront_audit_log_service: self.storefront_audit_log_service.expect("storefront_audit_log_service is required"),
            website_sale_setting_service: self.website_sale_setting_service.expect("website_sale_setting_service is required"),
        }
    }
}
