//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    cart_handler::create_cart_read_routes,
    cart_line_handler::create_cart_line_read_routes,
    checkout_session_handler::create_checkout_session_read_routes,
    product_listing_handler::create_product_listing_read_routes,
    product_price_handler::create_product_price_read_routes,
    recovery_invite_handler::create_recovery_invite_read_routes,
    shopper_party_handler::create_shopper_party_read_routes,
    storefront_audit_log_handler::create_storefront_audit_log_read_routes,
    website_sale_setting_handler::create_website_sale_setting_read_routes,
};

use crate::application::service::{
    CartService,
    CartLineService,
    CheckoutSessionService,
    ProductListingService,
    ProductPriceService,
    RecoveryInviteService,
    ShopperPartyService,
    StorefrontAuditLogService,
    WebsiteSaleSettingService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub cart: Arc<CartService>,
    pub cart_line: Arc<CartLineService>,
    pub checkout_session: Arc<CheckoutSessionService>,
    pub product_listing: Arc<ProductListingService>,
    pub product_price: Arc<ProductPriceService>,
    pub recovery_invite: Arc<RecoveryInviteService>,
    pub shopper_party: Arc<ShopperPartyService>,
    pub storefront_audit_log: Arc<StorefrontAuditLogService>,
    pub website_sale_setting: Arc<WebsiteSaleSettingService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Cart routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_cart_read_routes(services.cart))
        // CartLine routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_cart_line_read_routes(services.cart_line))
        // CheckoutSession routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_checkout_session_read_routes(services.checkout_session))
        // ProductListing routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_product_listing_read_routes(services.product_listing))
        // ProductPrice routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_product_price_read_routes(services.product_price))
        // RecoveryInvite routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_recovery_invite_read_routes(services.recovery_invite))
        // ShopperParty routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_shopper_party_read_routes(services.shopper_party))
        // StorefrontAuditLog routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_storefront_audit_log_read_routes(services.storefront_audit_log))
        // WebsiteSaleSetting routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_website_sale_setting_read_routes(services.website_sale_setting))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn cart_routes(service: Arc<CartService>) -> Router {
        create_cart_routes(service)
    }

    pub fn cart_line_routes(service: Arc<CartLineService>) -> Router {
        create_cart_line_routes(service)
    }

    pub fn checkout_session_routes(service: Arc<CheckoutSessionService>) -> Router {
        create_checkout_session_routes(service)
    }

    pub fn product_listing_routes(service: Arc<ProductListingService>) -> Router {
        create_product_listing_routes(service)
    }

    pub fn product_price_routes(service: Arc<ProductPriceService>) -> Router {
        create_product_price_routes(service)
    }

    pub fn recovery_invite_routes(service: Arc<RecoveryInviteService>) -> Router {
        create_recovery_invite_routes(service)
    }

    pub fn shopper_party_routes(service: Arc<ShopperPartyService>) -> Router {
        create_shopper_party_routes(service)
    }

    pub fn storefront_audit_log_routes(service: Arc<StorefrontAuditLogService>) -> Router {
        create_storefront_audit_log_routes(service)
    }

    pub fn website_sale_setting_routes(service: Arc<WebsiteSaleSettingService>) -> Router {
        create_website_sale_setting_routes(service)
    }

}
