//! Public events for Storefront module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CART EVENTS
// ============================================================================

/// Event published when a Cart is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartCreatedEvent {
    pub id: CartId,
    pub data: CartDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Cart is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartUpdatedEvent {
    pub id: CartId,
    pub data: CartDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Cart is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartDeletedEvent {
    pub id: CartId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CARTLINE EVENTS
// ============================================================================

/// Event published when a CartLine is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartLineCreatedEvent {
    pub id: CartLineId,
    pub data: CartLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CartLine is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartLineUpdatedEvent {
    pub id: CartLineId,
    pub data: CartLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CartLine is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartLineDeletedEvent {
    pub id: CartLineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHECKOUTSESSION EVENTS
// ============================================================================

/// Event published when a CheckoutSession is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckoutSessionCreatedEvent {
    pub id: CheckoutSessionId,
    pub data: CheckoutSessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CheckoutSession is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckoutSessionUpdatedEvent {
    pub id: CheckoutSessionId,
    pub data: CheckoutSessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CheckoutSession is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckoutSessionDeletedEvent {
    pub id: CheckoutSessionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PRODUCTLISTING EVENTS
// ============================================================================

/// Event published when a ProductListing is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductListingCreatedEvent {
    pub id: ProductListingId,
    pub data: ProductListingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProductListing is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductListingUpdatedEvent {
    pub id: ProductListingId,
    pub data: ProductListingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProductListing is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductListingDeletedEvent {
    pub id: ProductListingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PRODUCTPRICE EVENTS
// ============================================================================

/// Event published when a ProductPrice is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductPriceCreatedEvent {
    pub id: ProductPriceId,
    pub data: ProductPriceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProductPrice is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductPriceUpdatedEvent {
    pub id: ProductPriceId,
    pub data: ProductPriceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ProductPrice is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductPriceDeletedEvent {
    pub id: ProductPriceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// RECOVERYINVITE EVENTS
// ============================================================================

/// Event published when a RecoveryInvite is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryInviteCreatedEvent {
    pub id: RecoveryInviteId,
    pub data: RecoveryInviteDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RecoveryInvite is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryInviteUpdatedEvent {
    pub id: RecoveryInviteId,
    pub data: RecoveryInviteDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RecoveryInvite is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryInviteDeletedEvent {
    pub id: RecoveryInviteId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SHOPPERPARTY EVENTS
// ============================================================================

/// Event published when a ShopperParty is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopperPartyCreatedEvent {
    pub id: ShopperPartyId,
    pub data: ShopperPartyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ShopperParty is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopperPartyUpdatedEvent {
    pub id: ShopperPartyId,
    pub data: ShopperPartyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ShopperParty is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopperPartyDeletedEvent {
    pub id: ShopperPartyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// STOREFRONTAUDITLOG EVENTS
// ============================================================================

/// Event published when a StorefrontAuditLog is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontAuditLogCreatedEvent {
    pub id: StorefrontAuditLogId,
    pub data: StorefrontAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a StorefrontAuditLog is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontAuditLogUpdatedEvent {
    pub id: StorefrontAuditLogId,
    pub data: StorefrontAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a StorefrontAuditLog is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontAuditLogDeletedEvent {
    pub id: StorefrontAuditLogId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// WEBSITESALESETTING EVENTS
// ============================================================================

/// Event published when a WebsiteSaleSetting is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSaleSettingCreatedEvent {
    pub id: WebsiteSaleSettingId,
    pub data: WebsiteSaleSettingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a WebsiteSaleSetting is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSaleSettingUpdatedEvent {
    pub id: WebsiteSaleSettingId,
    pub data: WebsiteSaleSettingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a WebsiteSaleSetting is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSaleSettingDeletedEvent {
    pub id: WebsiteSaleSettingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Storefront module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum StorefrontEvent {
    CartCreated(CartCreatedEvent),
    CartUpdated(CartUpdatedEvent),
    CartDeleted(CartDeletedEvent),
    CartLineCreated(CartLineCreatedEvent),
    CartLineUpdated(CartLineUpdatedEvent),
    CartLineDeleted(CartLineDeletedEvent),
    CheckoutSessionCreated(CheckoutSessionCreatedEvent),
    CheckoutSessionUpdated(CheckoutSessionUpdatedEvent),
    CheckoutSessionDeleted(CheckoutSessionDeletedEvent),
    ProductListingCreated(ProductListingCreatedEvent),
    ProductListingUpdated(ProductListingUpdatedEvent),
    ProductListingDeleted(ProductListingDeletedEvent),
    ProductPriceCreated(ProductPriceCreatedEvent),
    ProductPriceUpdated(ProductPriceUpdatedEvent),
    ProductPriceDeleted(ProductPriceDeletedEvent),
    RecoveryInviteCreated(RecoveryInviteCreatedEvent),
    RecoveryInviteUpdated(RecoveryInviteUpdatedEvent),
    RecoveryInviteDeleted(RecoveryInviteDeletedEvent),
    ShopperPartyCreated(ShopperPartyCreatedEvent),
    ShopperPartyUpdated(ShopperPartyUpdatedEvent),
    ShopperPartyDeleted(ShopperPartyDeletedEvent),
    StorefrontAuditLogCreated(StorefrontAuditLogCreatedEvent),
    StorefrontAuditLogUpdated(StorefrontAuditLogUpdatedEvent),
    StorefrontAuditLogDeleted(StorefrontAuditLogDeletedEvent),
    WebsiteSaleSettingCreated(WebsiteSaleSettingCreatedEvent),
    WebsiteSaleSettingUpdated(WebsiteSaleSettingUpdatedEvent),
    WebsiteSaleSettingDeleted(WebsiteSaleSettingDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for StorefrontEventMetadata {
    fn default() -> Self {
        Self {
            module: "storefront",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
