//! Storefront Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Storefront exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use storefront::exports::{CartDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CartDto` - Data transfer object for Cart
/// - `CartSummary` - Summary view of Cart
/// - `CartId` - Type-safe ID wrapper
/// - `CartLineDto` - Data transfer object for CartLine
/// - `CartLineSummary` - Summary view of CartLine
/// - `CartLineId` - Type-safe ID wrapper
/// - `CheckoutSessionDto` - Data transfer object for CheckoutSession
/// - `CheckoutSessionSummary` - Summary view of CheckoutSession
/// - `CheckoutSessionId` - Type-safe ID wrapper
/// - `PickupLocationDto` - Data transfer object for PickupLocation
/// - `PickupLocationSummary` - Summary view of PickupLocation
/// - `PickupLocationId` - Type-safe ID wrapper
/// - `ProductListingDto` - Data transfer object for ProductListing
/// - `ProductListingSummary` - Summary view of ProductListing
/// - `ProductListingId` - Type-safe ID wrapper
/// - `ProductPriceDto` - Data transfer object for ProductPrice
/// - `ProductPriceSummary` - Summary view of ProductPrice
/// - `ProductPriceId` - Type-safe ID wrapper
/// - `RecoveryInviteDto` - Data transfer object for RecoveryInvite
/// - `RecoveryInviteSummary` - Summary view of RecoveryInvite
/// - `RecoveryInviteId` - Type-safe ID wrapper
/// - `ShopperPartyDto` - Data transfer object for ShopperParty
/// - `ShopperPartySummary` - Summary view of ShopperParty
/// - `ShopperPartyId` - Type-safe ID wrapper
/// - `WebsiteSaleSettingDto` - Data transfer object for WebsiteSaleSetting
/// - `WebsiteSaleSettingSummary` - Summary view of WebsiteSaleSetting
/// - `WebsiteSaleSettingId` - Type-safe ID wrapper
/// - `WishlistItemDto` - Data transfer object for WishlistItem
/// - `WishlistItemSummary` - Summary view of WishlistItem
/// - `WishlistItemId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `CartCreatedEvent` - Published when Cart is created
/// - `CartUpdatedEvent` - Published when Cart is updated
/// - `CartDeletedEvent` - Published when Cart is deleted
/// - `CartLineCreatedEvent` - Published when CartLine is created
/// - `CartLineUpdatedEvent` - Published when CartLine is updated
/// - `CartLineDeletedEvent` - Published when CartLine is deleted
/// - `CheckoutSessionCreatedEvent` - Published when CheckoutSession is created
/// - `CheckoutSessionUpdatedEvent` - Published when CheckoutSession is updated
/// - `CheckoutSessionDeletedEvent` - Published when CheckoutSession is deleted
/// - `PickupLocationCreatedEvent` - Published when PickupLocation is created
/// - `PickupLocationUpdatedEvent` - Published when PickupLocation is updated
/// - `PickupLocationDeletedEvent` - Published when PickupLocation is deleted
/// - `ProductListingCreatedEvent` - Published when ProductListing is created
/// - `ProductListingUpdatedEvent` - Published when ProductListing is updated
/// - `ProductListingDeletedEvent` - Published when ProductListing is deleted
/// - `ProductPriceCreatedEvent` - Published when ProductPrice is created
/// - `ProductPriceUpdatedEvent` - Published when ProductPrice is updated
/// - `ProductPriceDeletedEvent` - Published when ProductPrice is deleted
/// - `RecoveryInviteCreatedEvent` - Published when RecoveryInvite is created
/// - `RecoveryInviteUpdatedEvent` - Published when RecoveryInvite is updated
/// - `RecoveryInviteDeletedEvent` - Published when RecoveryInvite is deleted
/// - `ShopperPartyCreatedEvent` - Published when ShopperParty is created
/// - `ShopperPartyUpdatedEvent` - Published when ShopperParty is updated
/// - `ShopperPartyDeletedEvent` - Published when ShopperParty is deleted
/// - `WebsiteSaleSettingCreatedEvent` - Published when WebsiteSaleSetting is created
/// - `WebsiteSaleSettingUpdatedEvent` - Published when WebsiteSaleSetting is updated
/// - `WebsiteSaleSettingDeletedEvent` - Published when WebsiteSaleSetting is deleted
/// - `WishlistItemCreatedEvent` - Published when WishlistItem is created
/// - `WishlistItemUpdatedEvent` - Published when WishlistItem is updated
/// - `WishlistItemDeletedEvent` - Published when WishlistItem is deleted
pub struct ExportSummary;
