//! Public services for Storefront module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.


// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// The host compose seam consumes the module through these re-exports:
// the four ports (catalog/party/tax/notifier), the pricing + checkout
// surfaces, and the typed error. The host installs adapters over its
// own module handles; the refusing/unwired defaults keep an uncomposed
// module fail-closed instead of silently functional.

pub use crate::application::service::catalog_read_port::{
    CatalogPortError, CatalogReadPort, ItemSnapshot, RefusingCatalogReadPort,
};
pub use crate::application::service::notifier_port::{
    RecoveryDelivery, RecoveryMessage, RecoveryNotifier, UnwiredRecoveryNotifier,
};
pub use crate::application::service::party_write_port::{
    PartyPortError, PartyWritePort, RefusingPartyWritePort,
};
pub use crate::application::service::tax_resolve_port::{
    RefusingTaxResolvePort, TaxPortError, TaxResolvePort,
};
pub use crate::application::service::checkout_service::{CheckoutDeps, CheckoutRow};
pub use crate::application::service::pricing_service::PricedCartView;
pub use crate::application::service::storefront_error::StorefrontError;
// <<< CUSTOM SERVICES END >>>
