//! Public types for Storefront module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// CART TYPES
// ============================================================================

/// Type-safe ID for Cart
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CartId(pub Uuid);

impl CartId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CartId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CartId> for Uuid {
    fn from(id: CartId) -> Self {
        id.0
    }
}

/// Data transfer object for Cart
///
/// This is the public representation of Cart for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartDto {
    pub id: CartId,
    pub website_id: Uuid,
    pub visitor_id: Uuid,
    pub portal_user_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub state: StorefrontCartState,
    pub coupon_code: Option<String>,
    pub delivery_carrier_id: Option<Uuid>,
    pub placed_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Cart for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartSummary {
    pub id: CartId,
}

/// Reference to Cart for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartRef {
    pub id: CartId,
}

// ============================================================================
// CARTLINE TYPES
// ============================================================================

/// Type-safe ID for CartLine
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CartLineId(pub Uuid);

impl CartLineId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CartLineId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CartLineId> for Uuid {
    fn from(id: CartLineId) -> Self {
        id.0
    }
}

/// Data transfer object for CartLine
///
/// This is the public representation of CartLine for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartLineDto {
    pub id: CartLineId,
    pub cart_id: Uuid,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of CartLine for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartLineSummary {
    pub id: CartLineId,
}

/// Reference to CartLine for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CartLineRef {
    pub id: CartLineId,
}

// ============================================================================
// CHECKOUTSESSION TYPES
// ============================================================================

/// Type-safe ID for CheckoutSession
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CheckoutSessionId(pub Uuid);

impl CheckoutSessionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CheckoutSessionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CheckoutSessionId> for Uuid {
    fn from(id: CheckoutSessionId) -> Self {
        id.0
    }
}

/// Data transfer object for CheckoutSession
///
/// This is the public representation of CheckoutSession for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckoutSessionDto {
    pub id: CheckoutSessionId,
    pub cart_id: Uuid,
    pub website_id: Uuid,
    pub sales_order_id: Option<Uuid>,
    pub gateway_transaction_id: Option<Uuid>,
    pub provider_code: Option<String>,
    pub provider_reference: Option<String>,
    pub amount_total: Decimal,
    pub state: StorefrontCheckoutState,
    pub placed_at: Option<DateTime<Utc>>,
    pub settled_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of CheckoutSession for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckoutSessionSummary {
    pub id: CheckoutSessionId,
}

/// Reference to CheckoutSession for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckoutSessionRef {
    pub id: CheckoutSessionId,
}

// ============================================================================
// PRODUCTLISTING TYPES
// ============================================================================

/// Type-safe ID for ProductListing
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProductListingId(pub Uuid);

impl ProductListingId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProductListingId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProductListingId> for Uuid {
    fn from(id: ProductListingId) -> Self {
        id.0
    }
}

/// Data transfer object for ProductListing
///
/// This is the public representation of ProductListing for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductListingDto {
    pub id: ProductListingId,
    pub website_id: Uuid,
    pub item_id: Uuid,
    pub sale_ok: bool,
    pub is_published: bool,
    pub sequence: i32,
    pub media_urls: serde_json::Value,
    pub metadata: serde_json::Value,
}

/// Summary view of ProductListing for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductListingSummary {
    pub id: ProductListingId,
}

/// Reference to ProductListing for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductListingRef {
    pub id: ProductListingId,
}

// ============================================================================
// PRODUCTPRICE TYPES
// ============================================================================

/// Type-safe ID for ProductPrice
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProductPriceId(pub Uuid);

impl ProductPriceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProductPriceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProductPriceId> for Uuid {
    fn from(id: ProductPriceId) -> Self {
        id.0
    }
}

/// Data transfer object for ProductPrice
///
/// This is the public representation of ProductPrice for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductPriceDto {
    pub id: ProductPriceId,
    pub website_id: Uuid,
    pub item_id: Uuid,
    pub list_price: Decimal,
    pub compare_at_price: Option<Decimal>,
    pub currency: String,
    pub metadata: serde_json::Value,
}

/// Summary view of ProductPrice for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductPriceSummary {
    pub id: ProductPriceId,
}

/// Reference to ProductPrice for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductPriceRef {
    pub id: ProductPriceId,
}

// ============================================================================
// RECOVERYINVITE TYPES
// ============================================================================

/// Type-safe ID for RecoveryInvite
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RecoveryInviteId(pub Uuid);

impl RecoveryInviteId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RecoveryInviteId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RecoveryInviteId> for Uuid {
    fn from(id: RecoveryInviteId) -> Self {
        id.0
    }
}

/// Data transfer object for RecoveryInvite
///
/// This is the public representation of RecoveryInvite for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryInviteDto {
    pub id: RecoveryInviteId,
    pub cart_id: Uuid,
    pub template_ref: String,
    pub notified_at: Option<DateTime<Utc>>,
    pub delivery_state: String,
    pub metadata: serde_json::Value,
}

/// Summary view of RecoveryInvite for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryInviteSummary {
    pub id: RecoveryInviteId,
}

/// Reference to RecoveryInvite for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecoveryInviteRef {
    pub id: RecoveryInviteId,
}

// ============================================================================
// SHOPPERPARTY TYPES
// ============================================================================

/// Type-safe ID for ShopperParty
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ShopperPartyId(pub Uuid);

impl ShopperPartyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ShopperPartyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ShopperPartyId> for Uuid {
    fn from(id: ShopperPartyId) -> Self {
        id.0
    }
}

/// Data transfer object for ShopperParty
///
/// This is the public representation of ShopperParty for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopperPartyDto {
    pub id: ShopperPartyId,
    pub company_id: Uuid,
    pub email_normalized: String,
    pub party_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of ShopperParty for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopperPartySummary {
    pub id: ShopperPartyId,
}

/// Reference to ShopperParty for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShopperPartyRef {
    pub id: ShopperPartyId,
}

// ============================================================================
// STOREFRONTAUDITLOG TYPES
// ============================================================================

/// Type-safe ID for StorefrontAuditLog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct StorefrontAuditLogId(pub Uuid);

impl StorefrontAuditLogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for StorefrontAuditLogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<StorefrontAuditLogId> for Uuid {
    fn from(id: StorefrontAuditLogId) -> Self {
        id.0
    }
}

/// Data transfer object for StorefrontAuditLog
///
/// This is the public representation of StorefrontAuditLog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontAuditLogDto {
    pub id: StorefrontAuditLogId,
    pub website_id: Option<Uuid>,
    pub event: StorefrontAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub detail: Option<serde_json::Value>,
    pub occurred_at: DateTime<Utc>,
}

/// Summary view of StorefrontAuditLog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontAuditLogSummary {
    pub id: StorefrontAuditLogId,
}

/// Reference to StorefrontAuditLog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorefrontAuditLogRef {
    pub id: StorefrontAuditLogId,
}

// ============================================================================
// WEBSITESALESETTING TYPES
// ============================================================================

/// Type-safe ID for WebsiteSaleSetting
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WebsiteSaleSettingId(pub Uuid);

impl WebsiteSaleSettingId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WebsiteSaleSettingId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WebsiteSaleSettingId> for Uuid {
    fn from(id: WebsiteSaleSettingId) -> Self {
        id.0
    }
}

/// Data transfer object for WebsiteSaleSetting
///
/// This is the public representation of WebsiteSaleSetting for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSaleSettingDto {
    pub id: WebsiteSaleSettingId,
    pub website_id: Uuid,
    pub access_gate: StorefrontAccessGate,
    pub default_customer_group_id: Option<Uuid>,
    pub guest_party_id: Uuid,
    pub recovery_template_ref: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of WebsiteSaleSetting for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSaleSettingSummary {
    pub id: WebsiteSaleSettingId,
}

/// Reference to WebsiteSaleSetting for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebsiteSaleSettingRef {
    pub id: WebsiteSaleSettingId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
