//! Storefront Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CartService;
pub use application::service::CartLineService;
pub use application::service::CheckoutSessionService;
pub use application::service::ProductListingService;
pub use application::service::ProductPriceService;
pub use application::service::RecoveryInviteService;
pub use application::service::ShopperPartyService;
pub use application::service::StorefrontAuditLogService;
pub use application::service::WebsiteSaleSettingService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Storefront module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let storefront = StorefrontModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = storefront.all_crud_routes();
/// ```
pub struct StorefrontModule {
    pub(crate) cart_service: Arc<CartService>,
    pub(crate) cart_line_service: Arc<CartLineService>,
    pub(crate) checkout_session_service: Arc<CheckoutSessionService>,
    pub(crate) product_listing_service: Arc<ProductListingService>,
    pub(crate) product_price_service: Arc<ProductPriceService>,
    pub(crate) recovery_invite_service: Arc<RecoveryInviteService>,
    pub(crate) shopper_party_service: Arc<ShopperPartyService>,
    pub(crate) storefront_audit_log_service: Arc<StorefrontAuditLogService>,
    pub(crate) website_sale_setting_service: Arc<WebsiteSaleSettingService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl StorefrontModule {
    /// Create a new module builder
    pub fn builder() -> StorefrontModuleBuilder {
        StorefrontModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_cart_read_routes,
            create_cart_line_read_routes,
            create_checkout_session_read_routes,
            create_product_listing_read_routes,
            create_product_price_read_routes,
            create_recovery_invite_read_routes,
            create_shopper_party_read_routes,
            create_storefront_audit_log_read_routes,
            create_website_sale_setting_read_routes,
        };

        Router::new()
            .merge(create_cart_read_routes(self.cart_service.clone()))
            .merge(create_cart_line_read_routes(self.cart_line_service.clone()))
            .merge(create_checkout_session_read_routes(self.checkout_session_service.clone()))
            .merge(create_product_listing_read_routes(self.product_listing_service.clone()))
            .merge(create_product_price_read_routes(self.product_price_service.clone()))
            .merge(create_recovery_invite_read_routes(self.recovery_invite_service.clone()))
            .merge(create_shopper_party_read_routes(self.shopper_party_service.clone()))
            .merge(create_storefront_audit_log_read_routes(self.storefront_audit_log_service.clone()))
            .merge(create_website_sale_setting_read_routes(self.website_sale_setting_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_cart_read_routes,
            create_cart_line_read_routes,
            create_checkout_session_read_routes,
            create_product_listing_read_routes,
            create_product_price_read_routes,
            create_recovery_invite_read_routes,
            create_shopper_party_read_routes,
            create_storefront_audit_log_read_routes,
            create_website_sale_setting_read_routes,
        };

        Router::new()
            .merge(create_cart_read_routes(self.cart_service.clone()))
            .merge(create_cart_line_read_routes(self.cart_line_service.clone()))
            .merge(create_checkout_session_read_routes(self.checkout_session_service.clone()))
            .merge(create_product_listing_read_routes(self.product_listing_service.clone()))
            .merge(create_product_price_read_routes(self.product_price_service.clone()))
            .merge(create_recovery_invite_read_routes(self.recovery_invite_service.clone()))
            .merge(create_shopper_party_read_routes(self.shopper_party_service.clone()))
            .merge(create_storefront_audit_log_read_routes(self.storefront_audit_log_service.clone()))
            .merge(create_website_sale_setting_read_routes(self.website_sale_setting_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for StorefrontModule
pub struct StorefrontModuleBuilder {
    db_pool: Option<PgPool>,
}

impl StorefrontModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<StorefrontModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Cart service
        let cart_repository = Arc::new(CartRepository::new(db_pool.clone()));
        let cart_service = Arc::new(CartService::with_repository(cart_repository.clone()));

        // CartLine service
        let cart_line_repository = Arc::new(CartLineRepository::new(db_pool.clone()));
        let cart_line_service = Arc::new(CartLineService::with_repository(cart_line_repository.clone()));

        // CheckoutSession service
        let checkout_session_repository = Arc::new(CheckoutSessionRepository::new(db_pool.clone()));
        let checkout_session_service = Arc::new(CheckoutSessionService::with_repository(checkout_session_repository.clone()));

        // ProductListing service
        let product_listing_repository = Arc::new(ProductListingRepository::new(db_pool.clone()));
        let product_listing_service = Arc::new(ProductListingService::with_repository(product_listing_repository.clone()));

        // ProductPrice service
        let product_price_repository = Arc::new(ProductPriceRepository::new(db_pool.clone()));
        let product_price_service = Arc::new(ProductPriceService::with_repository(product_price_repository.clone()));

        // RecoveryInvite service
        let recovery_invite_repository = Arc::new(RecoveryInviteRepository::new(db_pool.clone()));
        let recovery_invite_service = Arc::new(RecoveryInviteService::with_repository(recovery_invite_repository.clone()));

        // ShopperParty service
        let shopper_party_repository = Arc::new(ShopperPartyRepository::new(db_pool.clone()));
        let shopper_party_service = Arc::new(ShopperPartyService::with_repository(shopper_party_repository.clone()));

        // StorefrontAuditLog service
        let storefront_audit_log_repository = Arc::new(StorefrontAuditLogRepository::new(db_pool.clone()));
        let storefront_audit_log_service = Arc::new(StorefrontAuditLogService::with_repository(storefront_audit_log_repository.clone()));

        // WebsiteSaleSetting service
        let website_sale_setting_repository = Arc::new(WebsiteSaleSettingRepository::new(db_pool.clone()));
        let website_sale_setting_service = Arc::new(WebsiteSaleSettingService::with_repository(website_sale_setting_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(StorefrontModule {
            cart_service,
            cart_line_service,
            checkout_session_service,
            product_listing_service,
            product_price_service,
            recovery_invite_service,
            shopper_party_service,
            storefront_audit_log_service,
            website_sale_setting_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for StorefrontModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
