//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod cart_handler;
pub mod cart_line_handler;
pub mod checkout_session_handler;
pub mod product_listing_handler;
pub mod product_price_handler;
pub mod recovery_invite_handler;
pub mod shopper_party_handler;
pub mod storefront_audit_log_handler;
pub mod website_sale_setting_handler;

// <<< CUSTOM
pub mod admin_routes;
pub mod public_routes;
// END CUSTOM

// Re-exports
pub use cart_handler::{create_cart_routes, create_cart_read_routes, create_cart_write_routes};
pub use cart_line_handler::{create_cart_line_routes, create_cart_line_read_routes, create_cart_line_write_routes};
pub use checkout_session_handler::{create_checkout_session_routes, create_checkout_session_read_routes, create_checkout_session_write_routes};
pub use product_listing_handler::{create_product_listing_routes, create_product_listing_read_routes, create_product_listing_write_routes};
pub use product_price_handler::{create_product_price_routes, create_product_price_read_routes, create_product_price_write_routes};
pub use recovery_invite_handler::{create_recovery_invite_routes, create_recovery_invite_read_routes, create_recovery_invite_write_routes};
pub use shopper_party_handler::{create_shopper_party_routes, create_shopper_party_read_routes, create_shopper_party_write_routes};
pub use storefront_audit_log_handler::{create_storefront_audit_log_routes, create_storefront_audit_log_read_routes, create_storefront_audit_log_write_routes};
pub use website_sale_setting_handler::{create_website_sale_setting_routes, create_website_sale_setting_read_routes, create_website_sale_setting_write_routes};
// <<< CUSTOM
pub use admin_routes::{storefront_admin_routes, StorefrontAdminState, StorefrontActor};
pub use public_routes::{
    storefront_error_response, storefront_public_routes, StorefrontPublicState, VISITOR_TOKEN_HEADER,
};
// END CUSTOM
